import { Destination, Cabin, Experience, BlogPost, Locale } from "@/types";

export const destinations: Destination[] = [
  {
    id: "1", slug: "lapland", name: { fi: "Lappi", es: "Laponia", en: "Lapland" },
    description: { fi: "Lappi on Suomen pohjoisin osa, jossa voit kokea aidot revontulet, huskyajelut ja lumiset maisemat. Täydellinen talviloma.", es: "Laponia es la región más septentrional de Finlandia, donde podrás vivir las auténticas auroras boreales, paseos en husky y paisajes nevados. Ideal para unas vacaciones de invierno.", en: "Lapland is Finland's northernmost region, where you can experience authentic Northern Lights, husky rides and snowy landscapes. Perfect for a winter holiday." },
    shortDescription: { fi: "Revontulet, huskyt ja arktinen taika", es: "Auroras, huskies y magia ártica", en: "Northern Lights, huskies & arctic magic" },
    region: "North", images: ["https://images.unsplash.com/photo-1483347756197-71ef80e95f73?w=1200","https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=1200"], priceFrom: 890, featured: true, coordinates: { lat: 67.9222, lng: 26.5046 }, tags: ["northern-lights","winter","adventure"]
  },
  {
    id: "2", slug: "helsinki", name: { fi: "Helsinki", es: "Helsinki", en: "Helsinki" },
    description: { fi: "Suomen pääkaupunki yhdistää modernin designin, merellisen ilmapiirin ja rikkaan kulttuurin. Design District, Suomenlinna ja saunakulttuuri odottavat.", es: "La capital de Finlandia combina diseño moderno, ambiente marítimo y rica cultura. Design District, Suomenlinna y la cultura del sauna te esperan.", en: "Finland's capital combines modern design, maritime atmosphere and rich culture. Design District, Suomenlinna and sauna culture await." },
    shortDescription: { fi: "Design, meri ja kaupunkikulttuuri", es: "Diseño, mar y cultura urbana", en: "Design, sea & urban culture" },
    region: "South", images: ["https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?w=1200","https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200"], priceFrom: 450, featured: true, coordinates: { lat: 60.1699, lng: 24.9384 }, tags: ["city","culture","design"]
  },
  {
    id: "3", slug: "tampere", name: { fi: "Tampere", es: "Tampere", en: "Tampere" },
    description: { fi: "Suomen saunapääkaupunki järvien välissä. Teollisuushistoria, moderni kulttuuri ja maan parhaat saunat.", es: "La capital del sauna de Finlandia entre lagos. Historia industrial, cultura moderna y los mejores saunas del país.", en: "Finland's sauna capital between lakes. Industrial history, modern culture and the country's best saunas." },
    shortDescription: { fi: "Saunat, järvet ja teollisuushistoria", es: "Saunas, lagos e historia industrial", en: "Saunas, lakes & industrial heritage" },
    region: "Central", images: ["https://images.unsplash.com/photo-1590073242678-70ee3fc28f8e?w=1200"], priceFrom: 380, featured: false, coordinates: { lat: 61.4978, lng: 23.7610 }, tags: ["sauna","lakes","culture"]
  },
  {
    id: "4", slug: "turku", name: { fi: "Turku", es: "Turku", en: "Turku" },
    description: { fi: "Suomen vanhin kaupunki ja entinen pääkaupunki. Saaristomeri, keskiaikainen linna ja elävä jokiranta.", es: "La ciudad más antigua de Finlandia y antigua capital. Mar de Archipiélago, castillo medieval y animado río.", en: "Finland's oldest city and former capital. Archipelago Sea, medieval castle and lively riverside." },
    shortDescription: { fi: "Historia, saaristo ja jokikulttuuri", es: "Historia, archipiélago y cultura fluvial", en: "History, archipelago & river culture" },
    region: "Southwest", images: ["https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=1200"], priceFrom: 420, featured: false, coordinates: { lat: 60.4518, lng: 22.2666 }, tags: ["history","archipelago","culture"]
  },
  {
    id: "5", slug: "archipelago", name: { fi: "Saaristo", es: "Archipiélago", en: "Archipelago" },
    description: { fi: "Yli 40 000 saarta, ainutlaatuinen luonto ja rauhalliset majakat. Suomen saaristo on Unescon maailmanperintökohde.", es: "Más de 40.000 islas, naturaleza única y faros tranquilos. El archipiélago finlandés es Patrimonio de la UNESCO.", en: "Over 40,000 islands, unique nature and peaceful lighthouses. Finland's archipelago is a UNESCO World Heritage site." },
    shortDescription: { fi: "40 000 saarta ja meren rauha", es: "40.000 islas y paz del mar", en: "40,000 islands & sea serenity" },
    region: "Southwest", images: ["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200"], priceFrom: 550, featured: true, coordinates: { lat: 60.2, lng: 21.5 }, tags: ["nature","islands","summer"]
  },
];

export const cabins: Cabin[] = [
  { id:"c1", slug:"aurora-cabin-lapland", name:{fi:"Aurora-mökki Lapissa",es:"Cabaña Aurora en Laponia",en:"Aurora Cabin in Lapland"}, description:{fi:"Ylellinen lasikattoinen mökki täydellisellä revontulinäkymällä. Oma sauna, takka ja täydellinen yksityisyys.",es:"Cabaña de lujo con techo de cristal y vista perfecta a las auroras. Sauna propia, chimenea y privacidad total.",en:"Luxury glass-roof cabin with perfect Northern Lights view. Private sauna, fireplace and complete privacy."}, location:"Rovaniemi area", region:"Lapland", pricePerNight:320, images:["https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=1200","https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=1200"], features:["glass-roof","sauna","fireplace","kitchen","wifi","northern-lights"], maxGuests:4, bedrooms:2, coordinates:{lat:66.5,lng:25.7}, type:"cabin" },
  { id:"c2", slug:"igloo-hotel-kakslauttanen", name:{fi:"Iglohotelli Kakslauttanen",es:"Hotel Igloo Kakslauttanen",en:"Igloo Hotel Kakslauttanen"}, description:{fi:"Maailmankuulu lasi-iglu, jossa nukut tähtien alla. Lämmitetty sänky ja revontulinäkymä suoraan sängystä.",es:"El famoso iglú de cristal donde duermes bajo las estrellas. Cama calefactada y vista a las auroras desde la cama.",en:"World-famous glass igloo where you sleep under the stars. Heated bed and Northern Lights view from bed."}, location:"Saariselkä", region:"Lapland", pricePerNight:450, images:["https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200"], features:["glass-igloo","heated-bed","restaurant","activities"], maxGuests:2, bedrooms:1, coordinates:{lat:68.4,lng:27.4}, type:"igloo" },
  { id:"c3", slug:"lake-villa-tampere", name:{fi:"Järvimökki Tampereella",es:"Villa del Lago en Tampere",en:"Lake Villa in Tampere"}, description:{fi:"Rauhallinen mökki järven rannalla, oma laituri ja savusauna. Täydellinen kesäloma.",es:"Cabaña tranquila a orillas del lago, con embarcadero propio y sauna de humo. Ideal para el verano.",en:"Peaceful lakeside cabin with private pier and smoke sauna. Perfect for summer holidays."}, location:"Tampere region", region:"Central", pricePerNight:180, images:["https://images.unsplash.com/photo-1499696010180-025ef6e1a8f9?w=1200"], features:["lake-access","smoke-sauna","boat","kitchen","terrace"], maxGuests:6, bedrooms:3, coordinates:{lat:61.5,lng:23.8}, type:"villa" },
  { id:"c4", slug:"design-hotel-helsinki", name:{fi:"Design-hotelli Helsinki",es:"Hotel de Diseño Helsinki",en:"Design Hotel Helsinki"}, description:{fi:"Tyylikäs boutique-hotelli Design Districtissä. Skandinaavista designia, kattoterassi ja erinomainen sijainti.",es:"Elegante hotel boutique en el Design District. Diseño escandinavo, terraza en la azotea y excelente ubicación.",en:"Stylish boutique hotel in the Design District. Scandinavian design, rooftop terrace and excellent location."}, location:"Helsinki Design District", region:"South", pricePerNight:195, images:["https://images.unsplash.com/photo-1566073772120-0500485d835d?w=1200"], features:["design","rooftop","breakfast","central","spa"], maxGuests:2, bedrooms:1, coordinates:{lat:60.16,lng:24.94}, type:"hotel" },
];

export const experiences: Experience[] = [
  { id:"e1", slug:"northern-lights-hunt", name:{fi:"Revontulijahti",es:"Caza de Auroras Boreales",en:"Northern Lights Hunt"}, description:{fi:"Ammattimainen opas vie sinut parhaisiin revontulipaikkoihin. Sisältää lämpimät vaatteet, kuumaa juomaa ja valokuvausvinkkejä.",es:"Un guía profesional te lleva a los mejores lugares para ver auroras. Incluye ropa de abrigo, bebida caliente y consejos de fotografía.",en:"A professional guide takes you to the best Northern Lights spots. Includes warm clothing, hot drinks and photography tips."}, shortDescription:{fi:"Aito revontulikokemus ammattilaisen kanssa",es:"Experiencia auténtica de auroras con profesional",en:"Authentic Northern Lights experience with a pro"}, price:149, duration:"3-4h", images:["https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=1200"], category:"northern-lights", region:"Lapland", maxParticipants:12 },
  { id:"e2", slug:"husky-safari", name:{fi:"Huskyajelu",es:"Safari en Husky",en:"Husky Safari"}, description:{fi:"Aja omaa valjakkoa kauniissa talvimaisemassa. Sisältää johdannon koiriin ja lämpimän juoman jälkeen.",es:"Conduce tu propio trineo en un hermoso paisaje invernal. Incluye introducción a los perros y bebida caliente después.",en:"Drive your own sled team through beautiful winter landscapes. Includes introduction to the dogs and hot drink after."}, shortDescription:{fi:"Oma valjakko lumisessa erämaassa",es:"Tu propio trineo en la nieve",en:"Your own sled team in the snowy wilderness"}, price:189, duration:"2h", images:["https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=1200"], category:"husky", region:"Lapland", maxParticipants:8 },
  { id:"e3", slug:"traditional-sauna", name:{fi:"Perinteinen savusauna",es:"Sauna de Humo Tradicional",en:"Traditional Smoke Sauna"}, description:{fi:"Koe aito suomalainen savusauna järven rannalla. Vihtominen, avanto ja tarinat kuuluvat kokemukseen.",es:"Vive la auténtica sauna de humo finlandesa a orillas del lago. Incluye ramas de abedul, agujero en el hielo e historias.",en:"Experience authentic Finnish smoke sauna by the lake. Includes birch whisk, ice hole and stories."}, shortDescription:{fi:"Aito savusauna + avanto",es:"Sauna de humo auténtica + agujero de hielo",en:"Authentic smoke sauna + ice hole"}, price:79, duration:"2.5h", images:["https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1200"], category:"sauna", region:"Central", maxParticipants:10 },
  { id:"e4", slug:"archipelago-cruise", name:{fi:"Saaristoristeily",es:"Crucero por el Archipiélago",en:"Archipelago Cruise"}, description:{fi:"Päiväristeily kauniissa saaristossa. Lounas, uimamahdollisuus ja majakkavierailu.",es:"Crucero diurno por el hermoso archipiélago. Almuerzo, posibilidad de nadar y visita a un faro.",en:"Day cruise in the beautiful archipelago. Lunch, swimming opportunity and lighthouse visit."}, shortDescription:{fi:"Päivä merellä saarten keskellä",es:"Un día en el mar entre islas",en:"A day at sea among the islands"}, price:95, duration:"6h", images:["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200"], category:"cruise", region:"Southwest", maxParticipants:40 },
  { id:"e5", slug:"reindeer-farm", name:{fi:"Porotila ja ajelu",es:"Granja de Renos y Paseo",en:"Reindeer Farm & Ride"}, description:{fi:"Vierailu perinteisellä porotilalla. Ruoki poroja, aja pororeellä ja kuule tarinoita saamelaiskulttuurista.",es:"Visita a una granja de renos tradicional. Alimenta renos, pasea en trineo de renos y escucha historias de la cultura sami.",en:"Visit a traditional reindeer farm. Feed reindeer, ride a reindeer sled and hear stories of Sámi culture."}, shortDescription:{fi:"Porot, saamelaiskulttuuri ja tarinat",es:"Renos, cultura sami e historias",en:"Reindeer, Sámi culture & stories"}, price:129, duration:"2.5h", images:["https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200"], category:"culture", region:"Lapland", maxParticipants:15 },
];

export const blogPosts: BlogPost[] = [
  { id:"b1", slug:"best-time-northern-lights", title:{fi:"Milloin nähdä revontulet Suomessa?",es:"¿Cuándo ver las auroras boreales en Finlandia?",en:"When is the best time to see Northern Lights in Finland?"}, excerpt:{fi:"Paras aika revontulille on syyskuusta maaliskuuhun. Tässä oppaassa kerromme kaiken tarpeellisen.",es:"La mejor época para las auroras es de septiembre a marzo. En esta guía te contamos todo lo necesario.",en:"The best time for Northern Lights is from September to March. In this guide we tell you everything you need."}, content:{fi:"Revontulet näkyvät parhaiten pimeinä, selkeinä öinä...",es:"Las auroras se ven mejor en noches oscuras y despejadas...",en:"Northern Lights are best seen on dark, clear nights..."}, image:"https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=1200", author:"Anna Virtanen", publishedAt:"2025-11-15", tags:["northern-lights","tips","winter"] },
  { id:"b2", slug:"finnish-sauna-guide", title:{fi:"Suomalaisen saunan täydellinen opas",es:"Guía completa de la sauna finlandesa",en:"The Complete Guide to Finnish Sauna"}, excerpt:{fi:"Sauna on suomalaisen sielun koti. Opi säännöt, tyypit ja miten nauttia siitä oikein.",es:"La sauna es el hogar del alma finlandesa. Aprende las reglas, tipos y cómo disfrutarla correctamente.",en:"Sauna is the home of the Finnish soul. Learn the rules, types and how to enjoy it properly."}, content:{fi:"Suomessa on yli 3 miljoonaa saunaa...",es:"En Finlandia hay más de 3 millones de saunas...",en:"There are over 3 million saunas in Finland..."}, image:"https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1200", author:"Mikko Korhonen", publishedAt:"2025-10-02", tags:["sauna","culture","tips"] },
];

export function getLocalized<T extends Record<Locale, string>>(obj: T, locale: Locale): string { return obj[locale] || obj.en; }
