export type PhotoCredit = {
  url: string;
  credit: string;
  license: string;
  sourcePage: string;
};

export const photoLibrary = {
  hero: "https://upload.wikimedia.org/wikipedia/commons/9/91/Mathildedal_harbour_sunset.jpg",
  helsinkiHarbour: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Helsinki_Harbour,_Satama,_Finland,_Suomi.jpg",
  tampereTammerkoski: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Tammerkoski_Tampere.jpg",
  mathildedalVillage: "https://upload.wikimedia.org/wikipedia/commons/0/08/Anttipoffi_workers%27_quarters_in_Mathildedal.jpg",
  mathildedalHarbour: "https://upload.wikimedia.org/wikipedia/commons/9/91/Mathildedal_harbour_sunset.jpg",
  naantaliOldTown: "https://upload.wikimedia.org/wikipedia/commons/9/9b/Old_Town_of_Naantali%2C_Finland.jpg",
  turkuAura: "https://upload.wikimedia.org/wikipedia/commons/6/6c/Aura_river_in_Turku.jpg",
  hanko: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Hanko_aerial_1.jpg",
  aland: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Kastelholm_2026-08-09_image12.jpg",
  teijoNationalPark: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Punassuo2.jpg",
  porvoo: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Porvoo_old_town.jpg",
  hankoAerial: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Hanko_aerial_1.jpg",
  hankoRegattaBeach: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Regattanranta_beach_in_the_city_center_of_Hanko,_Finland,_2021.jpg",
  sarkisalo: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Ulkoluotosilta3.jpg",
  turkuArchipelago: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Turku_Archipelago.jpg",
  turkuArchipelagoHouse: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Turku_archipelago_house.jpg",
  naantaliHarbour: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Naantali_harbour_and_church.jpg",
  hamina: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Raittiustalo_Hamina_2026-07-13_a.jpg",
  saloVeturitalli: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Veturitalli.jpg",
  sauna: "https://cdn-datahub.visitfinland.com/images/a2446f90-7cba-11ef-a1fa-c33120773bf0.png?s=1280",
  herrankukkaroSauna: "https://le-de.cdn-website.com/437c2bac51dd486c80c3e153a9033393/dms3rep/multi/opt/Kuva8-8066abf8-1920w.jpg",
  storfinnhova: "https://www.storfinnhova.com/wp-content/uploads/2025/10/080925-Kemio-tilakuvat-web-117_cropped.jpg",
  bjorkholm: "https://cdn.johku.com/bjorkholm/files/419/w374-h237-s/image.Svartan_Bjorkholm_johku_wallpaper.jpg",
  naturaVivaTeijo: "https://cdn.johku.com/naturaviva/largefiles/676/webp/teijo-national-park-rental-shop.webp",
  pumpkinWeeks: "https://visitsalo.fi/wp-content/uploads/sites/2/2025/08/Kurpitsapuistossa-pyoraileva-luuranko-450x253.jpg",
  mathildedalChristmas: "https://visitmathildedal.fi/sites/default/files/galleriakuvat/2026/valimo.jpg",
  rosalaVikingCentre: "https://cdn.johku.com/rosala/largefiles/577.jpg",
  rosalaVikingHall: "https://cdn.johku.com/rosala/largefiles/44-RVC%20hallen%20forneldar%202017.jpg",
} as const;

export const photoCredits: PhotoCredit[] = [
  { url: photoLibrary.helsinkiHarbour, credit: "Juha Agren", license: "CC BY-SA 4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Helsinki_Harbour,_Satama,_Finland,_Suomi.jpg" },
  { url: photoLibrary.tampereTammerkoski, credit: "Tiia Monto", license: "CC BY-SA 3.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Tammerkoski_Tampere.jpg" },
  { url: photoLibrary.mathildedalHarbour, credit: "Kotivalo", license: "CC BY-SA 4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Mathildedal_harbour_sunset.jpg" },
  { url: photoLibrary.mathildedalVillage, credit: "Kotivalo", license: "CC BY-SA 3.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Anttipoffi_workers%27_quarters_in_Mathildedal.jpg" },
  { url: photoLibrary.naantaliOldTown, credit: "Tatu Kosonen", license: "CC BY-SA 4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Old_Town_of_Naantali,_Finland.jpg" },
  { url: photoLibrary.turkuAura, credit: "Anssi Koskinen", license: "CC BY 2.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Aura_river_in_Turku.jpg" },
  { url: photoLibrary.hanko, credit: "Kallerna", license: "CC BY-SA 4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Hanko_aerial_1.jpg" },
  { url: photoLibrary.aland, credit: "Håkan Skogsjö", license: "CC BY-SA 4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Kastelholm_2026-08-09_image12.jpg" },
  { url: photoLibrary.teijoNationalPark, credit: "Vnnen", license: "CC BY-SA 4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Punassuo2.jpg" },
  { url: photoLibrary.porvoo, credit: "Teemu Eskola", license: "CC BY-SA 3.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Porvoo_old_town.jpg" },
  { url: photoLibrary.hankoAerial, credit: "Kallerna", license: "CC BY-SA 4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Hanko_aerial_1.jpg" },
  { url: photoLibrary.hankoRegattaBeach, credit: "W.carter", license: "CC BY-SA 4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Regattanranta_beach_in_the_city_center_of_Hanko,_Finland,_2021.jpg" },
  { url: photoLibrary.sarkisalo, credit: "Motopark", license: "CC BY-SA 3.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Ulkoluotosilta3.jpg" },
  { url: photoLibrary.turkuArchipelago, credit: "Rob Sinclair", license: "CC BY-SA 2.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Turku_Archipelago.jpg" },
  { url: photoLibrary.turkuArchipelagoHouse, credit: "Henri Sivonen", license: "CC BY 2.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Turku_archipelago_house.jpg" },
  { url: photoLibrary.naantaliHarbour, credit: "Pöllö", license: "CC BY-SA 3.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Naantali_harbour_and_church.jpg" },
  { url: photoLibrary.hamina, credit: "Htm", license: "CC BY-SA 4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Raittiustalo_Hamina_2026-07-13_a.jpg" },
  { url: photoLibrary.saloVeturitalli, credit: "Motopark", license: "Public domain", sourcePage: "https://commons.wikimedia.org/wiki/File:Veturitalli.jpg" },
  { url: photoLibrary.sauna, credit: "Visit Finland DataHub", license: "Provider/partner image", sourcePage: "https://www.visitfinland.com/" },
  { url: photoLibrary.herrankukkaroSauna, credit: "Herrankukkaro", license: "Provider website image", sourcePage: "https://www.herrankukkaro.fi/kokous/saunat-ja-kylvyt" },
  { url: photoLibrary.storfinnhova, credit: "Storfinnhova Gård", license: "Provider website image", sourcePage: "https://www.storfinnhova.com/" },
  { url: photoLibrary.bjorkholm, credit: "Björkholm mökit Oy", license: "Provider website image", sourcePage: "https://bjorkholm.johku.com/en_US/cottages/svartan-mokki" },
  { url: photoLibrary.naturaVivaTeijo, credit: "Natura Viva", license: "Provider website image", sourcePage: "https://naturaviva.fi/en_US/forest-hut-matildanjarvi/teijo-rental-shop" },
  { url: photoLibrary.pumpkinWeeks, credit: "Visit Salo / Kurpitsaviikot", license: "Visit Salo website image", sourcePage: "https://visitsalo.fi/kurpitsaviikot/" },
  { url: photoLibrary.mathildedalChristmas, credit: "Visit Mathildedal", license: "Visit Mathildedal website image", sourcePage: "https://visitmathildedal.fi/fi/valimo" },
  { url: photoLibrary.rosalaVikingCentre, credit: "Rosala & Bengtskär Booking Office / Rosala Viking Centre", license: "Provider/partner image", sourcePage: "https://rosala.johku.com/fi_FI/tietoa-varaustoimistosta" },
  { url: photoLibrary.rosalaVikingHall, credit: "Rosala & Bengtskär Booking Office / Rosala Viking Centre", license: "Provider/partner image", sourcePage: "https://rosala.johku.com/fi_FI/tietoa-varaustoimistosta" },
];
