import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, BedDouble, Flame, Landmark, Ship, Waves } from "lucide-react";
import type { Locale } from "@/types";
import { buildLocalizedMetadata } from "@/lib/seo";

const copy={
fi:{title:"Kemiönsaari & Rosala – saariston historia ja meri",desc:"Kemiönsaari-opas: Rosala, Kasnäs, Bengtskär, majoitus, ruoka, sauna ja merielämykset.",eyebrow:"KEMIÖNSAARI · TURUN SAARISTO",intro:"Kemiönsaari yhdistää pienet saaristokylät, ulkomeren, historialliset kohteet ja rauhalliset yöpymiset. Rosala ja Kasnäs ovat erityisen hyviä lähtöpisteitä saariston kokemiseen.",rosala:"Rosalan Viikinkikeskus",rosalaText:"Viikinkikylä ja Bed & Breakfast tekevät Rosalan historiasta konkreettisen. Majoitukseen voi yhdistää iltasaunan ja aamiaisen, ja kylässä voi kokeilla viikinkihenkisiä aktiviteetteja.",kasnas:"Kasnäs – saariston tukikohta",kasnasText:"Kasnäs toimii ympäri vuoden. Hotelli, kylpylä, ravintola, kauppa ja vierasvenesatama ovat samassa merellisessä ympäristössä, ja retkiä lähtee Bengtskärin, Rosalan ja Örön suuntaan.",beng:"Bengtskär & ulkomeri",bengText:"Bengtskärin majakka on klassinen saaristoretki. Matka merellä, avoimet maisemat ja kohteen historia tekevät retkestä osan itse kokemusta.",stay:"Majoitus",stayText:"Kemiönsaaren tarjonta ulottuu hotelleista ja kylpylästä mökkeihin, glampingiin, caravaniin ja ulkosaariston majoituksiin.",food:"Ruoka",foodText:"Kasnäsin ravintola korostaa saariston makuja ja paikallisia sesonkiraaka-aineita. Saaristossa pienet kahvilat ja ravintolat ovat osa matkan rytmiä.",sauna:"Sauna & hyvinvointi",saunaText:"Kasnäsissä on rantasauna, spa ja ulkoporeallas. Rosalan Viking Centre Bed & Breakfast sisältää iltasaunan ja aamiaisen.",official:"Tutustu Visit Kemiöniin",coastal:"Takaisin Rannikon Suomi -oppaaseen"},
es:{title:"Kemiönsaari & Rosala – historia y mar del archipiélago",desc:"Guía de Kemiönsaari: Rosala, Kasnäs, Bengtskär, alojamiento, gastronomía, sauna y experiencias marítimas.",eyebrow:"KEMIÖNSAARI · ARCHIPIÉLAGO DE TURKU",intro:"Kemiönsaari reúne pueblos insulares, mar abierto, patrimonio y alojamientos tranquilos. Rosala y Kasnäs son excelentes puntos de partida para descubrir el archipiélago.",rosala:"Centro Vikingo de Rosala",rosalaText:"El pueblo vikingo y su Bed & Breakfast acercan la historia de Rosala a la vida actual. La estancia incluye sauna nocturna y desayuno, y el poblado ofrece actividades inspiradas en los vikingos.",kasnas:"Kasnäs – base del archipiélago",kasnasText:"Kasnäs funciona durante todo el año con hotel, spa, restaurante, tienda y puerto deportivo. Desde aquí parten excursiones hacia Bengtskär, Rosala y Örö.",beng:"Bengtskär y el mar abierto",bengText:"El faro de Bengtskär es una excursión clásica del archipiélago. El trayecto por mar, los paisajes abiertos y la historia forman parte de la experiencia.",stay:"Alojamiento",stayText:"Hay hoteles, spa, cabañas, glamping, camping y alojamientos en las islas exteriores.",food:"Gastronomía",foodText:"El restaurante de Kasnäs destaca los sabores del archipiélago y los ingredientes locales de temporada. Los pequeños cafés y restaurantes completan la ruta.",sauna:"Sauna y bienestar",saunaText:"Kasnäs ofrece sauna junto al mar, spa y jacuzzi exterior. El Bed & Breakfast del Centro Vikingo de Rosala incluye sauna nocturna y desayuno.",official:"Descubre Visit Kemiönsaari",coastal:"Volver a la guía de Finlandia costera"},
en:{title:"Kimitoön & Rosala – archipelago history and the sea",desc:"Kimitoön guide: Rosala, Kasnäs, Bengtskär, accommodation, food, sauna and maritime experiences.",eyebrow:"KIMITOÖN · TURKU ARCHIPELAGO",intro:"Kimitoön combines island villages, open sea, heritage and peaceful places to stay. Rosala and Kasnäs are strong starting points for exploring the archipelago.",rosala:"Rosala Viking Centre",rosalaText:"The Viking village and Bed & Breakfast bring Rosala's history to life. The stay includes an evening sauna and breakfast, with Viking-inspired activities in the village.",kasnas:"Kasnäs – an archipelago base",kasnasText:"Kasnäs operates year-round with a hotel, spa, restaurant, shop and guest harbour. Excursions head towards Bengtskär, Rosala and Örö.",beng:"Bengtskär & open sea",bengText:"The Bengtskär lighthouse is a classic archipelago excursion. The sea journey, open landscapes and history are all part of the experience.",stay:"Accommodation",stayText:"Kimitoön offers hotels, spa stays, cottages, glamping, camping and outer-island accommodation.",food:"Food",foodText:"Kasnäs restaurant focuses on archipelago flavours and local seasonal ingredients. Small cafés and restaurants add character along the route.",sauna:"Sauna & wellbeing",saunaText:"Kasnäs offers a seaside sauna, spa and outdoor hot tub. A Rosala Viking Centre Bed & Breakfast stay includes an evening sauna and breakfast.",official:"Explore Visit Kimitoön",coastal:"Back to the Coastal Finland guide"}
} as const;

export async function generateMetadata({params}:{params: Promise<{ locale: string }>}):Promise<Metadata>{const locale=(await params).locale as Locale;const x=copy[locale]||copy.en;return buildLocalizedMetadata({locale,title:x.title,description:x.desc,path:"kimitoon"});}
export default async function KimitoonPage({params}:{params: Promise<{ locale: string }>}){const locale=(await params).locale as Locale;const x=copy[locale]||copy.en;const cards=[[Landmark,x.rosala,x.rosalaText,"https://rosala.fi/"],[Waves,x.kasnas,x.kasnasText,"https://www.visitkimitoon.fi/en/destinations/hotel-kasnas/"],[Ship,x.beng,x.bengText,"https://www.visitkimitoon.fi/en/"]];return <main className="bg-white">
<section className="relative overflow-hidden bg-brand-950 text-white"><div className="absolute inset-0 bg-gradient-to-br from-brand-700 via-brand-950 to-brand-950"/><p className="absolute bottom-4 right-4 z-10 text-xs text-white/70">{locale === "fi" ? "Kohdekuva lisätään käyttöoikeuden vahvistamisen jälkeen" : locale === "es" ? "La foto se añadirá cuando se confirmen los derechos de uso" : "A destination photo will be added once usage rights are confirmed"}</p><div className="absolute inset-0 bg-gradient-to-t from-brand-950 via-brand-950/65 to-brand-950/10"/><div className="container-narrow relative py-24 sm:py-32"><p className="text-xs font-bold uppercase tracking-[.24em] text-gold-300">{x.eyebrow}</p><h1 className="mt-5 max-w-5xl font-display text-5xl font-bold leading-[.95] sm:text-7xl lg:text-8xl">{x.title}</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/80 sm:text-2xl">{x.intro}</p><div className="mt-8 flex flex-wrap gap-3"><a href="https://www.visitkimitoon.fi/en/" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-full bg-white px-6 py-3.5 text-sm font-bold text-brand-950">{x.official}<ArrowUpRight className="h-4 w-4"/></a><Link href={`/${locale}/coastal-finland#mathildedal`} className="inline-flex items-center gap-2 rounded-full border border-white/40 px-6 py-3.5 text-sm font-bold">{x.coastal}<ArrowRight className="h-4 w-4"/></Link></div></div></section>
<section className="container-narrow py-14 sm:py-20"><div className="grid gap-6 lg:grid-cols-3">{cards.map(([Icon,title,text,url])=>{const I=Icon as typeof Landmark;return <article key={title as string} className="rounded-[2rem] bg-brand-50 p-7 shadow-soft"><I className="h-7 w-7 text-brand-700"/><h2 className="mt-4 font-display text-3xl font-bold text-brand-950">{title as string}</h2><p className="mt-4 leading-8 text-slate-700">{text as string}</p><a href={url as string} target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-brand-800">{locale==="fi"?"Siirry kohteeseen":locale==="es"?"Ver el destino":"Explore"}<ArrowUpRight className="h-4 w-4"/></a></article>})}</div></section>
<section className="bg-brand-50 py-14 sm:py-20"><div className="container-narrow grid gap-6 md:grid-cols-3"><article className="rounded-[2rem] bg-white p-7 shadow-soft"><BedDouble className="h-7 w-7 text-brand-700"/><h2 className="mt-4 font-display text-3xl font-bold text-brand-950">{x.stay}</h2><p className="mt-4 leading-8 text-slate-700">{x.stayText}</p></article><article className="rounded-[2rem] bg-white p-7 shadow-soft"><Landmark className="h-7 w-7 text-brand-700"/><h2 className="mt-4 font-display text-3xl font-bold text-brand-950">{x.food}</h2><p className="mt-4 leading-8 text-slate-700">{x.foodText}</p></article><article className="rounded-[2rem] bg-white p-7 shadow-soft"><Flame className="h-7 w-7 text-amber-500"/><h2 className="mt-4 font-display text-3xl font-bold text-brand-950">{x.sauna}</h2><p className="mt-4 leading-8 text-slate-700">{x.saunaText}</p></article></div></section>
</main>}