"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
type Property={id:string;slug:string;status:string;property_type:string;region:string|null;base_price_eur:number|null;property_translations?:Array<{locale:string;name:string}>};
export default function PropertiesAdminPage(){
 const [items,setItems]=useState<Property[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 useEffect(()=>{fetch("/api/admin/properties",{cache:"no-store"}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||"Majoituksia ei voitu ladata");return b;}).then(b=>setItems(b.properties||[])).catch(e=>setError(e instanceof Error?e.message:"Lataus epäonnistui")).finally(()=>setLoading(false));},[]);
 return <main className="min-h-screen bg-slate-50 px-4 py-8 sm:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-emerald-700">CMS / Majoitukset</p><h1 className="mt-1 text-3xl font-bold text-slate-950">Majoitukset</h1></div><Link href="/admin/properties/new" className="rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white">+ Uusi majoitus</Link></div>{error&&<div className="mt-6 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}<div className="mt-8 overflow-hidden rounded-2xl border bg-white shadow-sm">{loading?<div className="p-8 text-slate-500">Ladataan…</div>:items.length===0?<div className="p-8 text-slate-500">Ei vielä majoituksia. Luo ensimmäinen kohde.</div>:<div className="divide-y">{items.map(item=><Link key={item.id} href={"/admin/properties/"+item.id} className="flex flex-col gap-2 p-5 hover:bg-slate-50 sm:flex-row sm:items-center sm:justify-between"><div><div className="font-semibold text-slate-950">{item.property_translations?.find(t=>t.locale==="es")?.name||item.property_translations?.[0]?.name||item.slug}</div><div className="text-sm text-slate-500">{item.region||"Suomi"} · {item.property_type} · {item.base_price_eur!=null?item.base_price_eur+" € / yö":"Hinta ei asetettu"}</div></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold">{item.status}</span></Link>)}</div>}</div></div></main>;
}
