'use client';

import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Save } from 'lucide-react';
import { useParams, useRouter } from 'next/navigation';

const input = 'mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-brand focus:ring-4 focus:ring-brand/10';

type FormState = { nameEs: string; nameFi: string; nameEn: string; slug: string; region: string; descriptionEs: string; descriptionFi: string; descriptionEn: string; imageUrl: string; status: 'draft' | 'published' };
const empty: FormState = { nameEs: '', nameFi: '', nameEn: '', slug: '', region: '', descriptionEs: '', descriptionFi: '', descriptionEn: '', imageUrl: '', status: 'published' };

export default function EditDestinationPage() {
  const params = useParams<{ id: string }>();
  const router = useRouter();
  const [form, setForm] = useState<FormState>(empty);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  useEffect(() => { (async () => { try { const response = await fetch('/api/admin/destinations', { cache: 'no-store' }); if (!response.ok) throw new Error('Kohteita ei voitu ladata'); const payload = await response.json(); const item = (payload.destinations || []).find((x: any) => String(x.id) === String(params.id)); if (!item) throw new Error('Kohdetta ei löytynyt'); const tr = item.destination_translations || []; const get = (lang: string) => tr.find((x: any) => x.language_code === lang) || {}; setForm({ nameEs: get('es').name || '', nameFi: get('fi').name || '', nameEn: get('en').name || '', slug: item.slug || '', region: item.region || '', descriptionEs: get('es').full_description || get('es').short_description || '', descriptionFi: get('fi').full_description || get('fi').short_description || '', descriptionEn: get('en').full_description || get('en').short_description || '', imageUrl: item.hero_image_url || '', status: item.status === 'published' ? 'published' : 'draft' }); } catch (e) { setError(e instanceof Error ? e.message : 'Lataus epäonnistui'); } finally { setLoading(false); } })(); }, [params.id]);
  function update(field: keyof FormState, value: string) { setForm((current) => ({ ...current, [field]: value })); }
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(''); try { const response = await fetch('/api/admin/destinations', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: Number(params.id), slug: form.slug.trim(), region: form.region.trim(), heroImageUrl: form.imageUrl.trim(), status: form.status, translations: { fi: { name: form.nameFi, fullDescription: form.descriptionFi, shortDescription: form.descriptionFi }, es: { name: form.nameEs, fullDescription: form.descriptionEs, shortDescription: form.descriptionEs }, en: { name: form.nameEn, fullDescription: form.descriptionEn, shortDescription: form.descriptionEn } } }) }); if (!response.ok) { const payload = await response.json().catch(() => ({})); throw new Error(payload.error || 'Tallennus epäonnistui'); } router.push('/admin/destinos'); } catch (e) { setError(e instanceof Error ? e.message : 'Tallennus epäonnistui'); } finally { setSaving(false); } }
  if (loading) return <main className="flex min-h-[70vh] items-center justify-center bg-slate-50"><div className="h-10 w-10 animate-spin rounded-full border-4 border-slate-200 border-t-brand" /></main>;
  return <main className="min-h-[75vh] bg-slate-50 py-10"><div className="container-site max-w-5xl"><Link href="/admin/destinos" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-midnight"><ArrowLeft className="h-4 w-4" /> Takaisin hallintaan</Link><div className="mt-6 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-card"><div className="bg-midnight px-6 py-8 text-white sm:px-10"><p className="text-sm font-bold uppercase tracking-[0.18em] text-terracotta">Content Manager</p><h1 className="mt-2 text-3xl font-bold">Muokkaa matkakohdetta</h1></div><form onSubmit={submit} className="space-y-8 p-6 sm:p-10"><div className="grid gap-5 sm:grid-cols-3">{([['nameFi','Suomi','Rovaniemi'],['nameEs','Español','Rovaniemi'],['nameEn','English','Rovaniemi']] as const).map(([field,label,placeholder]) => <label key={field} className="text-sm font-semibold text-slate-700">{label}<input required value={form[field]} onChange={(e)=>update(field,e.target.value)} className={input} placeholder={placeholder} /></label>)}</div><div className="grid gap-5 sm:grid-cols-3"><label className="text-sm font-semibold text-slate-700">Slug<input required value={form.slug} onChange={(e)=>update('slug',e.target.value)} className={input} /></label><label className="text-sm font-semibold text-slate-700">Alue<input required value={form.region} onChange={(e)=>update('region',e.target.value)} className={input} /></label><label className="text-sm font-semibold text-slate-700">Tila<select value={form.status} onChange={(e)=>update('status',e.target.value)} className={input}><option value="published">Julkaistu</option><option value="draft">Luonnos</option></select></label></div><div className="grid gap-5 lg:grid-cols-3">{([['descriptionFi','Suomi'],['descriptionEs','Español'],['descriptionEn','English']] as const).map(([field,label])=><label key={field} className="text-sm font-semibold text-slate-700">{label}<textarea required rows={8} value={form[field]} onChange={(e)=>update(field,e.target.value)} className={input} /></label>)}</div><label className="block text-sm font-semibold text-slate-700">Hero-kuvan URL<input value={form.imageUrl} onChange={(e)=>update('imageUrl',e.target.value)} className={input} /></label>{error && <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</div>}<div className="flex justify-end border-t border-slate-100 pt-6"><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-brand px-7 py-3.5 text-sm font-bold text-white shadow-lg hover:bg-brand-dark disabled:opacity-60"><Save className="h-4 w-4" />{saving ? 'Tallennetaan...' : 'Tallenna muutokset'}</button></div></form></div></div></main>;
}
