import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Bike, BedDouble, Coffee, Flame, Ship, Waves } from "lucide-react";
import type { Locale } from "@/types";
import { buildLocalizedMetadata } from "@/lib/seo";
import { photoLibrary } from "@/lib/photo-library";

const c={
fi:{title:"Ahvenanmaa – saaristoreitti, pyöräily ja oma rauha",description:"Ahvenanmaa-opas: saaristoreitti, pyöräily, mökit, hotellit, ruoka, luonto, saunat ja pienet saaristokunnat.",eyebrow:"ÅLAND · SAARISTOMAAILMA",intro:"Ahvenanmaa on saaristomatka, jossa siirtyminen saarelta toiselle kuuluu kokemukseen. Pyörä, lautta, pieni kylä, merenranta ja pitkä ilta muodostavat rytmin, jossa itse matka on tärkeä osa lomaa.",cycling:"Pyöräily ja saaristoreitti",cyclingText:"Ahvenanmaan saaristoreitti kulkee pääsaarelta ulkosaariston kautta kohti Suomen rannikkoa. Vaihtoehtoja on pohjoiseen ja etelään, ja matkaan voi yhdistää Suomen saaristoreitin.",stay:"Majoitus",stayText:"Valikoimassa on mökkejä, hotelleja, B&B-paikkoja, leirintää ja pieniä saaristokohteita. Merellinen mökki omalla saunalla tai oma pieni saari muuttaa loman rytmiä nopeasti.",food:"Ruoka",foodText:"Reitin varrella on ravintoloita, kahviloita, maatilakahviloita ja saaristokyliin liittyviä makuja. Kesäkaudella palveluja on eniten, joten aukiolo kannattaa tarkistaa etukäteen.",nature:"Luonto ja historia",natureText:"Kastelholm, Bomarsund, Lemströmin kanava, Jomala ja Mariehamnin museot antavat reitille kulttuuria, kun taas pienet saaret tuovat rauhaa ja meren läheisyyttä.",sauna:"Sauna",saunaText:"Monissa mökeissä on oma sauna, ja saaristossa on myös kylpylä- ja saunapalveluja. Yhdistä sauna uintiin, pyöräpäivään tai iltaan meren äärellä.",route:"Katso Ålandin saaristoreitti",official:"Tutustu Visit Ålandiin",coastal:"Takaisin Rannikon Suomi -oppaaseen"},
es:{title:"Åland – rutas del archipiélago, bicicleta y tranquilidad",description:"Guía de Åland: rutas del archipiélago, ciclismo, cabañas, hoteles, gastronomía, naturaleza y sauna.",eyebrow:"ÅLAND · UN MUNDO DE ISLAS",intro:"Åland es un viaje donde el desplazamiento entre islas forma parte de la experiencia. Bicicleta, ferri, pequeños pueblos, mar y tardes largas crean un ritmo propio.",cycling:"Bicicleta y ruta del archipiélago",cyclingText:"La ruta del archipiélago de Åland cruza la isla principal y continúa hacia el archipiélago exterior por rutas norte y sur, y puede combinarse con la ruta del archipiélago finlandés.",stay:"Alojamiento",stayText:"Hay cabañas, hoteles, B&B, camping y pequeños alojamientos insulares. Una cabaña junto al mar con sauna privada puede cambiar por completo el ritmo del viaje.",food:"Gastronomía",foodText:"La ruta conecta restaurantes, cafés, granjas y pequeños pueblos gastronómicos. En verano hay más servicios, por lo que conviene comprobar horarios antes de salir.",nature:"Naturaleza e historia",natureText:"Kastelholm, Bomarsund, el canal de Lemström, Jomala y los museos de Mariehamn aportan cultura; las islas pequeñas aportan calma y mar.",sauna:"Sauna",saunaText:"Muchas cabañas cuentan con sauna privada y también hay spa y saunas en el archipiélago. Combina sauna con baño, bicicleta o una tarde junto al mar.",route:"Ver la ruta del archipiélago de Åland",official:"Descubre Visit Åland",coastal:"Volver a la guía de Finlandia costera"},
en:{title:"Åland – archipelago routes, cycling and island calm",description:"Åland guide: archipelago routes, cycling, cottages, hotels, food, nature and sauna.",eyebrow:"ÅLAND · A WORLD OF ISLANDS",intro:"Åland is a journey where moving between islands is part of the experience. Bike, ferry, small villages, sea and long evenings create a rhythm of their own.",cycling:"Cycling & the archipelago trail",cyclingText:"The Åland Archipelago Trail crosses the main island and continues through the outer archipelago on northern and southern routes, with the option to combine it with Finland's Archipelago Trail.",stay:"Accommodation",stayText:"Choose from cottages, hotels, B&Bs, camping and small island stays. A seaside cottage with a private sauna can completely change the pace of a holiday.",food:"Food",foodText:"The route connects restaurants, cafés, farm cafés and small island food destinations. Summer brings the most services, so check opening hours ahead.",nature:"Nature & history",natureText:"Kastelholm, Bomarsund, Lemström Canal, Jomala and Mariehamn's museums add culture, while smaller islands bring quiet and open sea.",sauna:"Sauna",saunaText:"Many cottages have a private sauna, and there are also spa and sauna services across the islands. Pair sauna with a swim, bike day or evening by the sea.",route:"View the Åland Archipelago Trail",official:"Explore Visit Åland",coastal:"Back to the Coastal Finland guide"}
} as const;

const links=[["Åland cycling","https://visitaland.com/en/experience/outdoor/cycle-in-aland/"],["Archipelago Trail","https://visitaland.com/en/experience/outdoor/cycle-in-aland/the-aland-archipelago-trail/"],["Cottages","https://visitaland.com/en/accommodation/cottage/"],["Hotels","https://visitaland.com/en/accommodation/hotel/"],["Visit Åland","https://visitaland.com/en/"]] as const;

export async function generateMetadata({params}:{params: Promise<{ locale: string }>}):Promise<Metadata>{const locale=(await params).locale as Locale;const x=c[locale]||c.en;return buildLocalizedMetadata({locale,title:x.title,description:x.description,path:"aland",image:photoLibrary.aland});}
export default async function AlandPage({params}:{params: Promise<{ locale: string }>}){const locale=(await params).locale as Locale;const x=c[locale]||c.en;return <main className="bg-white">
<section className="relative overflow-hidden bg-brand-950 text-white"><Image src={photoLibrary.aland} alt={x.title} fill priority sizes="100vw" className="object-cover opacity-45"/><div className="absolute inset-0 bg-gradient-to-t from-brand-950 via-brand-950/65 to-brand-950/10"/><div className="container-narrow relative py-24 sm:py-32"><p className="text-xs font-bold uppercase tracking-[.24em] text-gold-300">{x.eyebrow}</p><h1 className="mt-5 max-w-5xl font-display text-5xl font-bold leading-[.95] sm:text-7xl lg:text-8xl">{x.title}</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/80 sm:text-2xl">{x.intro}</p><div className="mt-8 flex flex-wrap gap-3"><a href="https://visitaland.com/en/" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-full bg-white px-6 py-3.5 text-sm font-bold text-brand-950">{x.official}<ArrowUpRight className="h-4 w-4"/></a><Link href={`/${locale}/coastal-finland#aland`} className="inline-flex items-center gap-2 rounded-full border border-white/40 px-6 py-3.5 text-sm font-bold">{x.coastal}<ArrowRight className="h-4 w-4"/></Link></div></div></section>
<section className="container-narrow py-14 sm:py-20"><div className="grid gap-6 md:grid-cols-2"><article className="rounded-[2rem] bg-brand-50 p-7 shadow-soft"><Bike className="h-7 w-7 text-brand-700"/><h2 className="mt-4 font-display text-3xl font-bold text-brand-950">{x.cycling}</h2><p className="mt-4 leading-8 text-slate-700">{x.cyclingText}</p><a href="https://visitaland.com/en/experience/outdoor/cycle-in-aland/the-aland-archipelago-trail/" target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-brand-800">{x.route}<ArrowUpRight className="h-4 w-4"/></a></article><article className="rounded-[2rem] bg-brand-50 p-7 shadow-soft"><BedDouble className="h-7 w-7 text-brand-700"/><h2 className="mt-4 font-display text-3xl font-bold text-brand-950">{x.stay}</h2><p className="mt-4 leading-8 text-slate-700">{x.stayText}</p></article><article className="rounded-[2rem] bg-white p-7 shadow-soft border border-slate-200"><Coffee className="h-7 w-7 text-brand-700"/><h2 className="mt-4 font-display text-3xl font-bold text-brand-950">{x.food}</h2><p className="mt-4 leading-8 text-slate-700">{x.foodText}</p></article><article className="rounded-[2rem] bg-white p-7 shadow-soft border border-slate-200"><Waves className="h-7 w-7 text-brand-700"/><h2 className="mt-4 font-display text-3xl font-bold text-brand-950">{x.nature}</h2><p className="mt-4 leading-8 text-slate-700">{x.natureText}</p></article></div></section>
<section className="bg-brand-950 py-16 text-white sm:py-24"><div className="container-narrow"><div className="grid gap-8 lg:grid-cols-2 lg:items-center"><div><Flame className="h-7 w-7 text-gold-300"/><h2 className="mt-4 font-display text-4xl font-bold">{x.sauna}</h2><p className="mt-5 text-lg leading-8 text-white/70">{x.saunaText}</p></div><div className="grid gap-3 sm:grid-cols-2">{links.map(([name,url])=><a key={name} href={url} target="_blank" rel="noopener noreferrer" className="rounded-2xl border border-white/10 bg-white/5 p-5 hover:bg-white/10"><h3 className="font-semibold">{name}</h3><span className="mt-4 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.1em] text-gold-300">{locale==="fi"?"Avaa":locale==="es"?"Abrir":"Open"}<ArrowUpRight className="h-3.5 w-3.5"/></span></a>)}</div></div></div></section>
</main>}