"use client";
import {useState} from "react";import{useRouter}from"next/navigation";
type Locale="fi"|"es"|"en";const locales:Locale[]=["fi","es","en"];type T={name:string;shortDescription:string;description:string;locationName:string;seoTitle:string;seoDescription:string};
const empty=():T=>({name:"",shortDescription:"",description:"",locationName:"",seoTitle:"",seoDescription:""});
export default function NewPropertyPage(){
 const router=useRouter();const[locale,setLocale]=useState<Locale>("es");const[saving,setSaving]=useState(false);const[error,setError]=useState("");
 const[form,setForm]=useState({slug:"",propertyType:"cabin",region:"",maxGuests:4,bedrooms:2,bathrooms:1,basePriceEur:"",featured:false});
 const[translations,setTranslations]=useState<Record<Locale,T>>({fi:empty(),es:empty(),en:empty()});
 function updateT(field:keyof T,value:string){setTranslations(c=>({...c,[locale]:{...c[locale],[field]:value}}));}
 async function save(){setSaving(true);setError("");try{const r=await fetch("/api/admin/properties",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,maxGuests:Number(form.maxGuests),bedrooms:Number(form.bedrooms),bathrooms:Number(form.bathrooms),basePriceEur:form.basePriceEur?Number(form.basePriceEur):null,translations})});const b=await r.json();if(!r.ok)throw new Error(b.error||"Tallennus epäonnistui");router.push("/admin/properties");}catch(e){setError(e instanceof Error?e.message:"Tallennus epäonnistui");}finally{setSaving(false);}}
 return <main className="min-h-screen bg-slate-50 px-4 py-8 sm:px-8"><div className="mx-auto max-w-5xl"><div className="flex items-end justify-between"><div><p className="text-sm font-semibold text-emerald-700">CMS / Majoitukset</p><h1 className="mt-1 text-3xl font-bold text-slate-950">Uusi majoitus</h1></div><button onClick={()=>router.back()} className="text-sm font-semibold text-slate-600">Peruuta</button></div><div className="mt-8 grid gap-6 lg:grid-cols-[1fr_320px]"><section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="mb-6 flex gap-2">{locales.map(l=><button key={l} onClick={()=>setLocale(l)} className={"rounded-lg px-4 py-2 text-sm font-semibold "+(locale===l?"bg-slate-950 text-white":"bg-slate-100 text-slate-600")}>{l.toUpperCase()}</button>)}</div><div className="grid gap-5"><Field label={"Nimi ("+locale.toUpperCase()+")"} value={translations[locale].name} onChange={v=>updateT("name",v)}/><Field label="Lyhyt kuvaus" value={translations[locale].shortDescription} onChange={v=>updateT("shortDescription",v)}/><TextArea label="Kuvaus" value={translations[locale].description} onChange={v=>updateT("description",v)}/><Field label="Sijainti" value={translations[locale].locationName} onChange={v=>updateT("locationName",v)}/><Field label="SEO title" value={translations[locale].seoTitle} onChange={v=>updateT("seoTitle",v)}/><TextArea label="SEO description" value={translations[locale].seoDescription} onChange={v=>updateT("seoDescription",v)}/></div></section><aside className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="font-semibold">Perustiedot</h2><div className="mt-4 grid gap-4"><Field label="Slug" value={form.slug} onChange={v=>setForm({...form,slug:v})}/><Field label="Alue" value={form.region} onChange={v=>setForm({...form,region:v})}/><Field label="Tyyppi" value={form.propertyType} onChange={v=>setForm({...form,propertyType:v})}/><NumberField label="Vieraat" value={form.maxGuests} onChange={v=>setForm({...form,maxGuests:v})}/><NumberField label="Makuuhuoneet" value={form.bedrooms} onChange={v=>setForm({...form,bedrooms:v})}/><NumberField label="Kylpyhuoneet" value={form.bathrooms} onChange={v=>setForm({...form,bathrooms:v})}/><Field label="Hinta / yö (€)" value={form.basePriceEur} onChange={v=>setForm({...form,basePriceEur:v})}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Etusivun nosto</label></div><button disabled={saving} onClick={save} className="mt-6 w-full rounded-xl bg-emerald-700 px-4 py-3 font-semibold text-white disabled:opacity-50">{saving?"Tallennetaan…":"Tallenna luonnos"}</button>{error&&<p className="mt-4 text-sm text-red-600">{error}</p>}</aside></div></div></main>;
}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="grid gap-2 text-sm font-medium text-slate-700"><span>{label}</span><input value={value} onChange={e=>onChange(e.target.value)} className="rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-100"/></label>}
function TextArea({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="grid gap-2 text-sm font-medium text-slate-700"><span>{label}</span><textarea rows={6} value={value} onChange={e=>onChange(e.target.value)} className="rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-100"/></label>}
function NumberField({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <label className="grid gap-2 text-sm font-medium text-slate-700"><span>{label}</span><input type="number" min={0} value={value} onChange={e=>onChange(Number(e.target.value))} className="rounded-xl border border-slate-200 px-4 py-3"/></label>}
