"use client";
import { useEffect,useState } from "react";
type Settings={site_name:string;primary_color:string;secondary_color:string;accent_color:string;heading_font:string;body_font:string;whatsapp_number:string;contact_email:string;default_og_image:string};
export default function SettingsPage(){
 const [settings,setSettings]=useState<Settings>({site_name:"Finland Experience",primary_color:"#123C36",secondary_color:"#D8B477",accent_color:"#4C9AA8",heading_font:"Inter",body_font:"Inter",whatsapp_number:"",contact_email:"",default_og_image:""}); const [error,setError]=useState(""); const [saved,setSaved]=useState(false);
 useEffect(()=>{fetch("/api/admin/settings",{cache:"no-store"}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||"Asetuksia ei voitu ladata");setSettings(s=>({...s,...b.settings}));}).catch(e=>setError(e instanceof Error?e.message:"Lataus epäonnistui"));},[]);
 async function save(){setSaved(false);const r=await fetch("/api/admin/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(settings)});const b=await r.json();if(!r.ok){setError(b.error||"Tallennus epäonnistui");return;}setSettings(s=>({...s,...b.settings}));setSaved(true);}
 const field=(key:keyof Settings,label:string)=><label className="grid gap-2 text-sm font-medium text-slate-700"><span>{label}</span><input value={settings[key]||""} onChange={e=>setSettings({...settings,[key]:e.target.value})} className="rounded-xl border border-slate-200 px-4 py-3"/></label>;
 return <main className="min-h-screen bg-slate-50 px-4 py-8 sm:px-8"><div className="mx-auto max-w-4xl"><p className="text-sm font-semibold text-emerald-700">CMS / Asetukset</p><h1 className="mt-1 text-3xl font-bold text-slate-950">Design & yhteystiedot</h1><div className="mt-8 grid gap-5 rounded-2xl border bg-white p-6 md:grid-cols-2">{field("site_name","Sivuston nimi")}{field("primary_color","Pääväri")}{field("secondary_color","Toissijainen väri")}{field("accent_color","Korostusväri")}{field("heading_font","Otsikkofontti")}{field("body_font","Leipätekstifontti")}{field("whatsapp_number","WhatsApp-numero")}{field("contact_email","Sähköposti")}{field("default_og_image","OG-kuvan URL")}</div><button onClick={save} className="mt-6 rounded-xl bg-slate-950 px-6 py-3 font-semibold text-white">Tallenna asetukset</button>{saved&&<p className="mt-3 text-sm text-emerald-700">Tallennettu.</p>}{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}</div></main>;
}
