import type { Addon } from '@/types';

export const MOCK_ADDONS: Addon[] = [
  // Experience 1 Add-ons
  {
    id: 1,
    experienceId: 1,
    nameEs: 'Sesión Fotográfica Profesional',
    nameFi: 'Ammattimainen valokuvaus',
    descriptionEs: 'Fotografo profesional capturando tus momentos bajo las auroras',
    descriptionFi: 'Ammattimainen valokuvaaja kuvailee hetkiläsi revontulien alla',
    priceEur: 150,
    maxQuantity: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    experienceId: 1,
    nameEs: 'Cena Gourmet Ártica',
    nameFi: 'Gourmet Arktinen Illallinen',
    descriptionEs: 'Cena de tres platos con especialidades finlandesas',
    descriptionFi: 'Kolmen ruokalajin illallinen suomalaisilla erikoisuuksilla',
    priceEur: 80,
    maxQuantity: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Experience 2 Add-ons
  {
    id: 3,
    experienceId: 2,
    nameEs: 'Tratamiento Spa Completo',
    nameFi: 'Täydellinen Spa-hoito',
    descriptionEs: '90 minutos de masaje y tratamientos de spa',
    descriptionFi: '90 minuutin hieronta ja spa-hoidot',
    priceEur: 200,
    maxQuantity: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    experienceId: 2,
    nameEs: 'Noche en Iglú de Hielo',
    nameFi: 'Yö Jäähyttissä',
    descriptionEs: 'Noche en un iglú de hielo genuino con desayuno',
    descriptionFi: 'Yö aidossa jäähytissa aamiaisen kera',
    priceEur: 350,
    maxQuantity: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Experience 3 Add-ons
  {
    id: 5,
    experienceId: 3,
    nameEs: 'Encuentro con Cultura Sami',
    nameFi: 'Saamelaiskulttuurin tapaaminen',
    descriptionEs: 'Sesión interactiva con un guía sami',
    descriptionFi: 'Interaktiivinen istunto saamelaisoppaan kanssa',
    priceEur: 100,
    maxQuantity: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    experienceId: 3,
    nameEs: 'Equipo Fotográfico Profesional',
    nameFi: 'Ammattimainen valokuvauslaite',
    descriptionEs: 'Alquiler de cámara profesional con lentes',
    descriptionFi: 'Ammattimaisen kameran vuokraus linssillä',
    priceEur: 75,
    maxQuantity: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
