import type { Customer, Booking, BookingItem, Review } from '@/types';
import { BookingWorkflow } from '@/domain/booking';

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 1,
    email: 'maria.garcia@example.com',
    firstName: 'María',
    lastName: 'García',
    phone: '+34 912 345 678',
    country: 'ES',
    totalSpentEur: 1250,
    interests: 'auroras,naturaleza,aventura',
    leadSource: 'google',
    marketingConsent: true,
    createdAt: new Date('2026-01-15'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 2,
    email: 'carlos.lopez@example.com',
    firstName: 'Carlos',
    lastName: 'López',
    phone: '+34 933 456 789',
    country: 'ES',
    totalSpentEur: 2100,
    interests: 'sauna,relax,bienestar',
    leadSource: 'facebook',
    marketingConsent: true,
    createdAt: new Date('2026-02-01'),
    updatedAt: new Date('2026-02-01'),
  },
  {
    id: 3,
    email: 'sofia.martinez@example.com',
    firstName: 'Sofía',
    lastName: 'Martínez',
    phone: '+34 914 567 890',
    country: 'ES',
    totalSpentEur: 850,
    interests: 'huskies,aventura,familia',
    leadSource: 'instagram',
    marketingConsent: false,
    createdAt: new Date('2026-02-15'),
    updatedAt: new Date('2026-02-15'),
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 1,
    customerId: 1,
    bookingNumber: 'FEP-2W75N-ABC123',
    status: 'confirmed',
    totalPriceEur: 1350,
    paidPriceEur: 1350,
    paymentStatus: 'paid',
    cancellationReason: null,
    internalNotes: 'Cliente VIP, ofrecer upgrade',
    createdAt: new Date('2026-03-01'),
    updatedAt: new Date('2026-03-05'),
    confirmedAt: new Date('2026-03-05'),
    completedAt: null,
    cancelledAt: null,
  },
  {
    id: 2,
    customerId: 2,
    bookingNumber: 'FEP-2W75O-DEF456',
    status: 'payment_pending',
    totalPriceEur: 700,
    paidPriceEur: 0,
    paymentStatus: 'unpaid',
    cancellationReason: null,
    internalNotes: 'Reserva reciente, enviar recordatorio de pago',
    createdAt: new Date('2026-03-10'),
    updatedAt: new Date('2026-03-10'),
    confirmedAt: null,
    completedAt: null,
    cancelledAt: null,
  },
  {
    id: 3,
    customerId: 3,
    bookingNumber: 'FEP-2W75P-GHI789',
    status: 'inquiry',
    totalPriceEur: 500,
    paidPriceEur: 0,
    paymentStatus: 'unpaid',
    cancellationReason: null,
    internalNotes: 'Familias con niños, enviar información de seguridad',
    createdAt: new Date('2026-03-15'),
    updatedAt: new Date('2026-03-15'),
    confirmedAt: null,
    completedAt: null,
    cancelledAt: null,
  },
];

export const MOCK_BOOKING_ITEMS: BookingItem[] = [
  {
    id: 1,
    bookingId: 1,
    experienceId: 1,
    experienceDate: new Date('2026-04-15'),
    experienceTime: '20:00',
    adultCount: 2,
    childCount: 0,
    privateGroup: false,
    basePriceEur: 450,
    seasonalMultiplier: 1.0,
    totalPriceEur: 900,
    createdAt: new Date('2026-03-01'),
  },
  {
    id: 2,
    bookingId: 2,
    experienceId: 2,
    experienceDate: new Date('2026-05-20'),
    experienceTime: '14:00',
    adultCount: 2,
    childCount: 2,
    privateGroup: false,
    basePriceEur: 350,
    seasonalMultiplier: 0.9,
    totalPriceEur: 700,
    createdAt: new Date('2026-03-10'),
  },
  {
    id: 3,
    bookingId: 3,
    experienceId: 3,
    experienceDate: new Date('2026-06-10'),
    experienceTime: '10:00',
    adultCount: 2,
    childCount: 1,
    privateGroup: false,
    basePriceEur: 500,
    seasonalMultiplier: 1.0,
    totalPriceEur: 500,
    createdAt: new Date('2026-03-15'),
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 1,
    customerId: 1,
    bookingId: 1,
    experienceId: 1,
    rating: 5,
    titleEs: 'Una experiencia mágica bajo las auroras',
    titleFi: 'Taiallinen kokemus revontulien alla',
    commentEs:
      'Increíble. Los guías fueron muy profesionales y la experiencia fue inolvidable. Las auroras fueron espectaculares.',
    commentFi:
      'Hämmästyttävä. Oppaat olivat erittäin ammattitaitoisia ja kokemus oli muistettava. Revontulet olivat spektaakkelit.',
    status: 'published',
    publishedAt: new Date('2026-03-20'),
    createdAt: new Date('2026-03-20'),
    updatedAt: new Date('2026-03-20'),
  },
];
