import type { Inclusion, Exclusion } from '@/types';

export const MOCK_INCLUSIONS: Inclusion[] = [
  // Experience 1
  {
    id: 1,
    experienceId: 1,
    titleEs: 'Transporte en vehículo calefaccionado',
    titleFi: 'Kuljetus lämmitetyssä ajoneuvossa',
    sortOrder: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    experienceId: 1,
    titleEs: 'Guía experto en auroras boreales',
    titleFi: 'Revontuliin erikoistunut opas',
    sortOrder: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    experienceId: 1,
    titleEs: 'Bebidas calientes tradicionales (café, té, chocolate)',
    titleFi: 'Perinteisiä kuumia juomia (kahvi, tee, suklaa)',
    sortOrder: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    experienceId: 1,
    titleEs: 'Instrucción fotográfica básica',
    titleFi: 'Perusvalokuvausopastus',
    sortOrder: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    experienceId: 1,
    titleEs: 'Ropa térmica de invierno',
    titleFi: 'Talven lämpövaatteet',
    sortOrder: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Experience 2
  {
    id: 6,
    experienceId: 2,
    titleEs: 'Acceso a saunas tradicionales de leña',
    titleFi: 'Pääsy perinteisiin puulla lämmitettäviin saunoihin',
    sortOrder: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    experienceId: 2,
    titleEs: 'Baño en lago helado (voluntario)',
    titleFi: 'Kylpy jäälämpimässä järvessä (vapaaehtoinen)',
    sortOrder: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    experienceId: 2,
    titleEs: 'Cena gourmet finlandesa',
    titleFi: 'Gourmet-illallinen suomalaisittain',
    sortOrder: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9,
    experienceId: 2,
    titleEs: 'Masaje relajante de 30 minutos',
    titleFi: '30 minuutin rentoutumismassaasi',
    sortOrder: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 10,
    experienceId: 2,
    titleEs: 'Toallas y productos de cuidado',
    titleFi: 'Pyyhkeet ja hoitotuotteet',
    sortOrder: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Experience 3
  {
    id: 11,
    experienceId: 3,
    titleEs: 'Trineo tirado por perros huskies auténticos',
    titleFi: 'Aito husky-koirarekka',
    sortOrder: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 12,
    experienceId: 3,
    titleEs: 'Entrenamiento completo de conducción',
    titleFi: 'Täydellinen ajoharjoittelu',
    sortOrder: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 13,
    experienceId: 3,
    titleEs: 'Almuerzo tradicional alrededor de fogata',
    titleFi: 'Perinteinen lounas nuotion ympärillä',
    sortOrder: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 14,
    experienceId: 3,
    titleEs: 'Casco de seguridad homologado',
    titleFi: 'Sertifioitu turvakypärä',
    sortOrder: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 15,
    experienceId: 3,
    titleEs: 'Ropa de invierno profesional',
    titleFi: 'Ammattimainen talvivaaatetus',
    sortOrder: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const MOCK_EXCLUSIONS: Exclusion[] = [
  // Experience 1
  {
    id: 1,
    experienceId: 1,
    titleEs: 'Vuelos internacionales',
    titleFi: 'Kansainväliset lennot',
    sortOrder: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    experienceId: 1,
    titleEs: 'Alojamiento',
    titleFi: 'Majoitus',
    sortOrder: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    experienceId: 1,
    titleEs: 'Comidas no especificadas',
    titleFi: 'Muut kuin määritellyt ruoat',
    sortOrder: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    experienceId: 1,
    titleEs: 'Seguro de viaje',
    titleFi: 'Matkavakuutus',
    sortOrder: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Experience 2
  {
    id: 5,
    experienceId: 2,
    titleEs: 'Transporte al spa (a menos que esté en el mismo lugar)',
    titleFi: 'Kuljetus spaan (jos se ei ole samassa paikassa)',
    sortOrder: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    experienceId: 2,
    titleEs: 'Bebidas alcohólicas',
    titleFi: 'Alkoholijuomat',
    sortOrder: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    experienceId: 2,
    titleEs: 'Servicios médicos adicionales',
    titleFi: 'Lisäsairaanhoitopalvelut',
    sortOrder: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Experience 3
  {
    id: 8,
    experienceId: 3,
    titleEs: 'Vuelos y hotel',
    titleFi: 'Lennot ja hotelli',
    sortOrder: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9,
    experienceId: 3,
    titleEs: 'Transporte adicional después de la actividad',
    titleFi: 'Lisäkuljetus aktiviteetin jälkeen',
    sortOrder: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 10,
    experienceId: 3,
    titleEs: 'Bebidas alcohólicas',
    titleFi: 'Alkoholijuomat',
    sortOrder: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
