import type { Media } from '@/types';

export const MOCK_MEDIA: Media[] = [
  // Experience 1 - Aurora Borealis
  {
    id: 1,
    experienceId: 1,
    destinationId: null,
    mediaType: 'image',
    url: 'https://images.unsplash.com/photo-1579033100235-ba666c8cb4d0?w=1200&h=800&fit=crop',
    altTextEs: 'Aurora boreal verde en el cielo nocturno de Laponia',
    altTextFi: 'Vihreä revontuli Lapin yötaivaalla',
    captionEs: 'Aurora Boreal Típica',
    captionFi: 'Tyypillinen Revontuli',
    copyright: 'Unsplash',
    sortOrder: 1,
    isHero: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    experienceId: 1,
    destinationId: null,
    mediaType: 'image',
    url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop',
    altTextEs: 'Grupo viendo auroras boreales en la noche',
    altTextFi: 'Ryhmä katsomassa revontulia yöllä',
    captionEs: 'Experiencia en Grupo',
    captionFi: 'Ryhmäkokemus',
    copyright: 'Unsplash',
    sortOrder: 2,
    isHero: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Experience 2 - Sauna
  {
    id: 3,
    experienceId: 2,
    destinationId: null,
    mediaType: 'image',
    url: 'https://images.unsplash.com/photo-1544161515-81e9b8d4db5b?w=1200&h=800&fit=crop',
    altTextEs: 'Interior de sauna finlandesa tradicional',
    altTextFi: 'Perinteisen suomalaisen saunan sisäkuva',
    captionEs: 'Sauna Finlandesa Auténtica',
    captionFi: 'Aito Suomalainen Sauna',
    copyright: 'Unsplash',
    sortOrder: 1,
    isHero: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    experienceId: 2,
    destinationId: null,
    mediaType: 'image',
    url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&h=800&fit=crop',
    altTextEs: 'Vista de lago helado desde la sauna',
    altTextFi: 'Näkymä jäällä jäätyneestä järvestä saunasta',
    captionEs: 'Baño en Lago Helado',
    captionFi: 'Kylpy Jäässä',
    copyright: 'Unsplash',
    sortOrder: 2,
    isHero: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Experience 3 - Husky Sledding
  {
    id: 5,
    experienceId: 3,
    destinationId: null,
    mediaType: 'image',
    url: 'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=1200&h=800&fit=crop',
    altTextEs: 'Trineo tirado por huskies en bosque nevado',
    altTextFi: 'Husky-reki lumisessa metsässä',
    captionEs: 'Aventura en Trineo',
    captionFi: 'Reki-seikkailu',
    copyright: 'Unsplash',
    sortOrder: 1,
    isHero: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    experienceId: 3,
    destinationId: null,
    mediaType: 'image',
    url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop',
    altTextEs: 'Huskies descansando entre la nieve',
    altTextFi: 'Huskyt lepäävät lumessa',
    captionEs: 'Los Perros Huskies',
    captionFi: 'Husky-koirat',
    copyright: 'Unsplash',
    sortOrder: 2,
    isHero: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
