import type { PricingRule, SeasonalPricing } from '@/types';

export const MOCK_PRICING_RULES: PricingRule[] = [
  {
    id: 1,
    experienceId: 1,
    basePriceEur: 450,
    adultPriceEur: 450,
    childPriceEur: 350,
    childAgeMin: 6,
    childAgeMax: 17,
    privateGroupMultiplier: 1.5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    experienceId: 2,
    basePriceEur: 350,
    adultPriceEur: 350,
    childPriceEur: 250,
    childAgeMin: 8,
    childAgeMax: 17,
    privateGroupMultiplier: 1.3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    experienceId: 3,
    basePriceEur: 500,
    adultPriceEur: 500,
    childPriceEur: 400,
    childAgeMin: 10,
    childAgeMax: 17,
    privateGroupMultiplier: 1.4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const MOCK_SEASONAL_PRICING: SeasonalPricing[] = [
  {
    id: 1,
    experienceId: 1,
    seasonNameEs: 'Temporada Alta de Aurora',
    seasonNameFi: 'Revontuli-huippukausi',
    priceMultiplier: 1.4,
    startDate: new Date('2026-09-01'),
    endDate: new Date('2026-03-31'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    experienceId: 1,
    seasonNameEs: 'Temporada Baja',
    seasonNameFi: 'Matala sesonki',
    priceMultiplier: 0.8,
    startDate: new Date('2026-04-01'),
    endDate: new Date('2026-08-31'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    experienceId: 2,
    seasonNameEs: 'Verano',
    seasonNameFi: 'Kesä',
    priceMultiplier: 0.9,
    startDate: new Date('2026-06-01'),
    endDate: new Date('2026-08-31'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    experienceId: 3,
    seasonNameEs: 'Invierno',
    seasonNameFi: 'Talvi',
    priceMultiplier: 1.3,
    startDate: new Date('2026-11-01'),
    endDate: new Date('2027-03-31'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
