import { NextRequest, NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabase";
import { getAdminContext } from "@/lib/admin-auth";
const roles=["SUPER_ADMIN","ADMIN","CONTENT_MANAGER","EDITOR"];
async function auth(){const a=await getAdminContext();return a&&roles.includes(a.profile.role)?a:null;}
export async function GET(){const a=await getAdminContext();if(!a)return NextResponse.json({error:"Unauthorized"},{status:401});const {data,error}=await supabaseAdmin.from("site_banners").select("*").order("locale").order("sort_order");if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({banners:data||[]});}
export async function POST(req:NextRequest){if(!await auth())return NextResponse.json({error:"Forbidden"},{status:403});const b=await req.json();if(!["fi","es","en"].includes(b.locale)||!b.title)return NextResponse.json({error:"Kieli ja otsikko ovat pakollisia"},{status:400});const row={locale:b.locale,title:b.title,text:b.text||null,cta_label:b.cta_label||null,cta_url:b.cta_url||null,image_url:b.image_url||null,active:b.active!==false,start_at:b.start_at||null,end_at:b.end_at||null,sort_order:Number(b.sort_order||0)};const {data,error}=await supabaseAdmin.from("site_banners").insert(row).select("*").single();if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({banner:data});}
export async function PATCH(req:NextRequest){if(!await auth())return NextResponse.json({error:"Forbidden"},{status:403});const b=await req.json();if(!b.id)return NextResponse.json({error:"id puuttuu"},{status:400});const row={locale:b.locale,title:b.title,text:b.text||null,cta_label:b.cta_label||null,cta_url:b.cta_url||null,image_url:b.image_url||null,active:b.active!==false,start_at:b.start_at||null,end_at:b.end_at||null,sort_order:Number(b.sort_order||0)};const {data,error}=await supabaseAdmin.from("site_banners").update(row).eq("id",b.id).select("*").single();if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({banner:data});}
export async function DELETE(req:NextRequest){if(!await auth())return NextResponse.json({error:"Forbidden"},{status:403});const id=new URL(req.url).searchParams.get("id");if(!id)return NextResponse.json({error:"id puuttuu"},{status:400});const {error}=await supabaseAdmin.from("site_banners").delete().eq("id",id);if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({ok:true});}
