import { NextRequest, NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabase";
import { getAdminContext } from "@/lib/admin-auth";
import { isSafeUrlOrPath } from "@/lib/utils";
const roles=["SUPER_ADMIN","ADMIN","CONTENT_MANAGER"];
function validateUrl(value: unknown) {
  return value == null || value === "" || isSafeUrlOrPath(value);
}

async function auth(){const a=await getAdminContext();return a&&roles.includes(a.profile.role)?a:null;}
export async function GET(){const a=await getAdminContext();if(!a)return NextResponse.json({error:"Unauthorized"},{status:401});const {data,error}=await supabaseAdmin.from("site_banners").select("*").order("locale").order("sort_order");if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({banners:data||[]});}
export async function POST(req:NextRequest){if(!await auth())return NextResponse.json({error:"Forbidden"},{status:403});const b=await req.json();const sortOrder=Number(b.sort_order??0);if(!["fi","es","en"].includes(b.locale)||!String(b.title||"").trim()||!Number.isInteger(sortOrder)||sortOrder<0||!validateUrl(b.cta_url)||!validateUrl(b.image_url))return NextResponse.json({error:"Virheelliset bannerin tiedot"},{status:400});if(b.start_at&&Number.isNaN(Date.parse(b.start_at)))return NextResponse.json({error:"Virheellinen aloitusaika"},{status:400});if(b.end_at&&Number.isNaN(Date.parse(b.end_at)))return NextResponse.json({error:"Virheellinen lopetusaika"},{status:400});const row={locale:b.locale,title:String(b.title).trim(),text:b.text?String(b.text).trim():null,cta_label:b.cta_label?String(b.cta_label).trim():null,cta_url:b.cta_url?String(b.cta_url).trim():null,image_url:b.image_url?String(b.image_url).trim():null,active:b.active!==false,start_at:b.start_at||null,end_at:b.end_at||null,sort_order:sortOrder};const {data,error}=await supabaseAdmin.from("site_banners").insert(row).select("*").single();if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({banner:data});}
export async function PATCH(req:NextRequest){if(!await auth())return NextResponse.json({error:"Forbidden"},{status:403});const b=await req.json();const sortOrder=Number(b.sort_order??0);if(!b.id||!["fi","es","en"].includes(b.locale)||!String(b.title||"").trim()||!Number.isInteger(sortOrder)||sortOrder<0||!validateUrl(b.cta_url)||!validateUrl(b.image_url))return NextResponse.json({error:"Virheelliset bannerin tiedot"},{status:400});if(b.start_at&&Number.isNaN(Date.parse(b.start_at)))return NextResponse.json({error:"Virheellinen aloitusaika"},{status:400});if(b.end_at&&Number.isNaN(Date.parse(b.end_at)))return NextResponse.json({error:"Virheellinen lopetusaika"},{status:400});const row={locale:b.locale,title:String(b.title).trim(),text:b.text?String(b.text).trim():null,cta_label:b.cta_label?String(b.cta_label).trim():null,cta_url:b.cta_url?String(b.cta_url).trim():null,image_url:b.image_url?String(b.image_url).trim():null,active:b.active!==false,start_at:b.start_at||null,end_at:b.end_at||null,sort_order:sortOrder};const {data,error}=await supabaseAdmin.from("site_banners").update(row).eq("id",b.id).select("*").single();if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({banner:data});}
export async function DELETE(req:NextRequest){if(!await auth())return NextResponse.json({error:"Forbidden"},{status:403});const id=new URL(req.url).searchParams.get("id");if(!id)return NextResponse.json({error:"id puuttuu"},{status:400});const {error}=await supabaseAdmin.from("site_banners").delete().eq("id",id);if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({ok:true});}
