"use client";
import Link from "next/link";import{useEffect,useState}from"react";
type Banner={id:string;locale:"fi"|"es"|"en";title:string;text:string|null;cta_label:string|null;cta_url:string|null;image_url:string|null;active:boolean;start_at:string|null;end_at:string|null;sort_order:number};
const blank={locale:"fi" as const,title:"",text:"",cta_label:"",cta_url:"",image_url:"",active:true,start_at:"",end_at:"",sort_order:0};
export default function BannersAdmin(){const[banners,setBanners]=useState<Banner[]>([]);const[form,setForm]=useState(blank);const[editing,setEditing]=useState<string|null>(null);const[error,setError]=useState("");
async function load(){const r=await fetch("/api/admin/banners",{cache:"no-store"});const b=await r.json();if(!r.ok)throw Error(b.error);setBanners(b.banners||[])}useEffect(()=>{load().catch(e=>setError(e.message))},[]);
const set=(k:string,v:string|boolean|number)=>setForm(x=>({...x,[k]:v}));
async function save(){setError("");const r=await fetch("/api/admin/banners",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(editing?{...form,id:editing}:form)});const b=await r.json();if(!r.ok){setError(b.error||"Tallennus epäonnistui");return}setEditing(null);setForm(blank);await load()}
async function remove(id:string){if(!confirm("Poistetaanko banneri?"))return;await fetch("/api/admin/banners?id="+id,{method:"DELETE"});await load()}
function edit(b:Banner){setEditing(b.id);setForm({locale:b.locale,title:b.title,text:b.text||"",cta_label:b.cta_label||"",cta_url:b.cta_url||"",image_url:b.image_url||"",active:b.active,start_at:b.start_at?b.start_at.slice(0,16):"",end_at:b.end_at?b.end_at.slice(0,16):"",sort_order:b.sort_order})}
return <main className="min-h-screen bg-slate-50 px-4 py-8 sm:px-8"><div className="mx-auto max-w-6xl"><div className="flex items-end justify-between"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-emerald-700">CMS / Bannerit</p><h1 className="mt-2 text-3xl font-bold">Kampanjat ja bannerit</h1><p className="mt-2 text-slate-500">Ajasta tarjouksia, sesonkiviestejä ja toimintopainikkeita.</p></div><Link href="/admin/cms" className="text-sm font-semibold text-emerald-700">← CMS</Link></div>
<section className="mt-8 rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">{editing?"Muokkaa banneria":"Uusi banneri"}</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{<select value={form.locale} onChange={e=>set("locale",e.target.value)} className="rounded-xl border p-3"><option value="fi">Suomi</option><option value="es">Español</option><option value="en">English</option></select>}<input value={form.title} onChange={e=>set("title",e.target.value)} placeholder="Otsikko" className="rounded-xl border p-3"/><textarea value={form.text} onChange={e=>set("text",e.target.value)} placeholder="Teksti" className="rounded-xl border p-3 md:col-span-2"/><input value={form.cta_label} onChange={e=>set("cta_label",e.target.value)} placeholder="Painikkeen teksti" className="rounded-xl border p-3"/><input value={form.cta_url} onChange={e=>set("cta_url",e.target.value)} placeholder="/destinations" className="rounded-xl border p-3"/><input value={form.image_url} onChange={e=>set("image_url",e.target.value)} placeholder="Kuvan URL" className="rounded-xl border p-3 md:col-span-2"/><label className="grid gap-1 text-sm"><span>Alkaa</span><input type="datetime-local" value={form.start_at} onChange={e=>set("start_at",e.target.value)} className="rounded-xl border p-3"/></label><label className="grid gap-1 text-sm"><span>Päättyy</span><input type="datetime-local" value={form.end_at} onChange={e=>set("end_at",e.target.value)} className="rounded-xl border p-3"/></label><input type="number" value={form.sort_order} onChange={e=>set("sort_order",Number(e.target.value))} placeholder="Järjestys" className="rounded-xl border p-3"/><label className="flex items-center gap-2 rounded-xl border p-3"><input type="checkbox" checked={form.active} onChange={e=>set("active",e.target.checked)}/> Aktiivinen</label></div><div className="mt-4 flex gap-3"><button onClick={save} className="rounded-xl bg-slate-950 px-5 py-3 font-semibold text-white">{editing?"Tallenna":"Lisää banneri"}</button>{editing&&<button onClick={()=>{setEditing(null);setForm(blank)}} className="rounded-xl bg-slate-100 px-5 py-3">Peruuta</button>}</div>{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}</section>
<section className="mt-6 grid gap-4">{banners.map(b=><article key={b.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><span className="text-xs font-bold uppercase text-emerald-700">{b.locale}</span><h2 className="mt-1 text-xl font-semibold">{b.title}</h2><p className="mt-2 text-sm text-slate-500">{b.text}</p><p className="mt-3 text-xs text-slate-400">{b.start_at?"Alkaa "+new Date(b.start_at).toLocaleString("fi-FI"):"Heti"} · {b.end_at?"Päättyy "+new Date(b.end_at).toLocaleString("fi-FI"):"Ei päättymisaikaa"} · {b.active?"Aktiivinen":"Piilotettu"}</p></div><div className="flex gap-3 text-sm"><button onClick={()=>edit(b)} className="font-semibold text-emerald-700">Muokkaa</button><button onClick={()=>remove(b.id)} className="font-semibold text-red-600">Poista</button></div></div></article>)}</section>
</div></main>}
