'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Bot, Compass, Mail, MapPin, Search, Share2, Sparkles, Waves, Snowflake, TreePine, Star } from 'lucide-react';

type Language = 'fi' | 'es' | 'en';
const heroImage = 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=2200&q=90';
const destinationImages: Record<string, string> = { inari: heroImage, tampere: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200&q=85', helsinki: 'https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?w=1200&q=85', turku: 'https://images.unsplash.com/photo-1500534623283-312aade485b7?w=1200&q=85' };

const copy = {
  fi: { hero:'Koe Suomen taika – elämyksiä pohjoisesta etelään.', heroText:'Löydä Lapin revontulet, järvien rauha, Helsingin design ja saariston ainutlaatuinen tunnelma. Suunnittelemme matkoja, jotka tuntuvat Suomelta.', primary:'Tutustu elämyksiin', secondary:'Katso suosituimmat kohteet', trust:'Autenttisia suomalaisia kokemuksia', destTitle:'Löydä oma Suomesi', destText:'Valitse seuraava pysähdyspaikkasi. Jokainen kohde kertoo Suomesta omalla tavallaan.', search:'Hae kohdetta', expTitle:'Elämyksiä, joita et unohda', expText:'Valitse valmiista kokemuksista tai anna meidän rakentaa sinulle kokonainen matka.', blogTitle:'Inspiraatiota matkaasi', blogText:'Tarinoita, vinkkejä ja suomalaisia paikkoja matkasi suunnitteluun.', contactTitle:'Suunnitellaan sinun Suomen-matkasi', contactText:'Kerro millaista matkaa haaveilet. Autamme yhdistämään kohteet, elämykset ja oikean vuodenajan.', name:'Nimi', email:'Sähköposti', message:'Kerro matkatoiveestasi', send:'Lähetä matkapyyntö', aiTitle:'Kysy matka-asiantuntijalta', aiText:'AI auttaa löytämään kohteita kiinnostustesi, vuodenajan ja matkasi pituuden perusteella.', ask:'Kysy tekoälyltä', explore:'Tutustu' },
  es: { hero:'Descubre la magia de Finlandia – de norte a sur.', heroText:'Auroras en Laponia, lagos tranquilos, diseño en Helsinki y el encanto del archipiélago. Diseñamos viajes auténticamente finlandeses.', primary:'Ver experiencias', secondary:'Destinos populares', trust:'Experiencias finlandesas auténticas', destTitle:'Encuentra tu Finlandia', destText:'Elige tu próxima parada. Cada destino cuenta una historia diferente de Finlandia.', search:'Buscar destino', expTitle:'Experiencias para recordar', expText:'Elige una experiencia o deja que diseñemos tu viaje completo.', blogTitle:'Inspiración para tu viaje', blogText:'Historias, consejos y lugares finlandeses para planificar tu viaje.', contactTitle:'Diseñemos tu viaje a Finlandia', contactText:'Cuéntanos qué sueñas con vivir. Te ayudamos a combinar destinos, experiencias y la mejor temporada.', name:'Nombre', email:'Correo electrónico', message:'Cuéntanos tu viaje', send:'Enviar solicitud', aiTitle:'Habla con nuestro asesor de viajes', aiText:'La IA puede recomendar destinos según tus intereses, temporada y duración del viaje.', ask:'Preguntar a la IA', explore:'Explorar' },
  en: { hero:'Experience the magic of Finland – from north to south.', heroText:'Northern Lights in Lapland, peaceful lakes, Helsinki design and the unique archipelago. We create journeys that feel authentically Finnish.', primary:'Explore experiences', secondary:'View popular destinations', trust:'Authentic Finnish experiences', destTitle:'Find your Finland', destText:'Choose your next stop. Every destination tells a different Finnish story.', search:'Search destination', expTitle:'Experiences to remember', expText:'Choose a ready-made experience or let us design your complete journey.', blogTitle:'Inspiration for your journey', blogText:'Stories, practical tips and Finnish places to help plan your trip.', contactTitle:'Let’s plan your Finland journey', contactText:'Tell us what you dream of experiencing. We will combine destinations, experiences and the right season.', name:'Name', email:'Email', message:'Tell us about your trip', send:'Send travel request', aiTitle:'Ask our travel advisor', aiText:'AI can recommend destinations based on your interests, season and trip length.', ask:'Ask the AI', explore:'Explore' },
} as const;

const destinations = [
  { slug:'inari', fi:['Inari','Aitoa Lappia, revontulia ja saamelaiskulttuuria.'], es:['Inari','La Laponia más auténtica, auroras y cultura sami.'], en:['Inari','Authentic Lapland, auroras and Sámi culture.'] },
  { slug:'tampere', fi:['Tampere','Järviä, saunoja ja elämyksellistä kaupunkikulttuuria.'], es:['Tampere','Lagos, saunas y una vibrante cultura urbana.'], en:['Tampere','Lakes, saunas and vibrant city culture.'] },
  { slug:'helsinki', fi:['Helsinki','Designia, merta, arkkitehtuuria ja saaristoa.'], es:['Helsinki','Diseño nórdico, mar, arquitectura y archipiélago.'], en:['Helsinki','Nordic design, sea, architecture and archipelago.'] },
  { slug:'turku', fi:['Turku','Historiaa, Aurajoki ja ainutlaatuinen saaristo.'], es:['Turku','Historia, río Aura y un archipiélago único.'], en:['Turku','History, the Aura River and a unique archipelago.'] },
];
const experiences = [
  { icon:Snowflake, fi:['Revontulet','Opastettu ilta Lapin parhaisiin revontulimaisemiin.'], es:['Auroras boreales','Una noche guiada para encontrar las mejores auroras.'], en:['Northern Lights','A guided night beneath the Northern Lights.'] },
  { icon:TreePine, fi:['Husky-safari','Talvinen seikkailu arktisen luonnon keskellä.'], es:['Safari en husky','Aventura invernal en plena naturaleza ártica.'], en:['Husky safari','A winter adventure through Arctic nature.'] },
  { icon:Waves, fi:['Sauna & järvi','Perinteinen sauna järven rannalla ja virkistävä uinti.'], es:['Sauna y lago','Sauna tradicional junto al lago y baño refrescante.'], en:['Sauna & lake','Traditional sauna by the lake and a refreshing swim.'] },
  { icon:Compass, fi:['Helsinki Design','Designia, arkkitehtuuria ja kahviloita paikallisen oppaan kanssa.'], es:['Diseño en Helsinki','Diseño, arquitectura y cafés con un guía local.'], en:['Helsinki design','Design, architecture and cafés with a local guide.'] },
];

export default function HomePage() {
  const [language, setLanguage] = useState<Language>('fi');
  const [search, setSearch] = useState('');
  const t = copy[language];
  useEffect(() => { const lang = new URLSearchParams(window.location.search).get('lang'); if (lang === 'fi' || lang === 'es' || lang === 'en') setLanguage(lang); }, []);
  const filtered = useMemo(() => destinations.filter((d) => `${d[language][0]} ${d[language][1]}`.toLowerCase().includes(search.toLowerCase())), [language, search]);

  return <main className="bg-white text-slate-900">
    <section className="relative min-h-[720px] overflow-hidden bg-midnight text-white sm:min-h-[800px]">
      <img src={heroImage} alt="Finnish landscape" className="absolute inset-0 h-full w-full object-cover" />
      <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(7,26,43,.95)_0%,rgba(7,26,43,.68)_48%,rgba(7,26,43,.20)_100%)]" /><div className="absolute inset-0 bg-[linear-gradient(0deg,rgba(7,26,43,.80),transparent_50%)]" />
      <div className="container-site relative flex min-h-[720px] items-center py-24 sm:min-h-[800px]"><div className="max-w-4xl pt-12">
        <div className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-4 py-2 text-sm font-bold backdrop-blur-md"><Sparkles className="h-4 w-4 text-terracotta" /> {t.trust}</div>
        <h1 className="mt-7 max-w-4xl text-5xl font-extrabold leading-[1.02] tracking-[-0.04em] sm:text-6xl lg:text-8xl">{t.hero}</h1>
        <p className="mt-7 max-w-2xl text-lg leading-8 text-white/80 sm:text-xl">{t.heroText}</p>
        <div className="mt-10 flex flex-col gap-3 sm:flex-row"><Link href="/experiencias" className="inline-flex items-center justify-center gap-2 rounded-full bg-white px-7 py-4 text-sm font-extrabold text-brand shadow-2xl transition hover:-translate-y-0.5 hover:bg-slate-50">{t.primary}<ArrowRight className="h-4 w-4" /></Link><a href="#destinations" className="inline-flex items-center justify-center rounded-full bg-white px-7 py-4 text-sm font-extrabold text-brand shadow-2xl transition hover:-translate-y-0.5 hover:bg-slate-50">{t.secondary}</a></div>
        <div className="mt-12 flex flex-wrap gap-7 text-sm text-white/70"><span>✓ Local knowledge</span><span>✓ Carefully selected experiences</span><span>✓ FI · ES · EN</span></div>
      </div></div>
    </section>

    <section id="destinations" className="container-site py-20 sm:py-28"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-2xl"><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-terracotta">Finland · Destinations</p><h2 className="mt-3 text-4xl font-extrabold tracking-tight text-midnight sm:text-5xl">{t.destTitle}</h2><p className="mt-4 text-lg leading-8 text-slate-600">{t.destText}</p></div><div className="flex items-center gap-3 rounded-2xl border border-slate-200 bg-white px-4 py-3 shadow-sm lg:w-80"><Search className="h-5 w-5 text-slate-400" /><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder={t.search} className="w-full bg-transparent text-sm outline-none" /></div></div><div className="mt-12 grid gap-7 sm:grid-cols-2 lg:grid-cols-4">{filtered.map((d)=><Link href={`/destinos/${d.slug}`} key={d.slug} className="group"><article className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-card transition duration-300 hover:-translate-y-1 hover:shadow-2xl"><div className="relative h-64 overflow-hidden"><img src={destinationImages[d.slug]} alt={d[language][0]} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-midnight/70 via-transparent to-transparent" /><span className="absolute left-4 top-4 rounded-full bg-white/90 px-3 py-1.5 text-xs font-bold text-midnight"><MapPin className="mr-1 inline h-3.5 w-3.5 text-brand" /> Finland</span></div><div className="p-6"><h3 className="text-2xl font-extrabold tracking-tight text-midnight">{d[language][0]}</h3><p className="mt-3 min-h-[58px] text-sm leading-6 text-slate-600">{d[language][1]}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-extrabold text-brand">{t.explore}<ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></div></article></Link>)}</div></section>

    <section id="experiences" className="bg-slate-50 py-20 sm:py-28"><div className="container-site"><div className="max-w-2xl"><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-terracotta">Curated experiences</p><h2 className="mt-3 text-4xl font-extrabold tracking-tight text-midnight sm:text-5xl">{t.expTitle}</h2><p className="mt-4 text-lg leading-8 text-slate-600">{t.expText}</p></div><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{experiences.map((e)=>{const Icon=e.icon;return <Link href="/experiencias" key={e[language][0]} className="group rounded-3xl border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-card"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-terracotta-soft text-terracotta"><Icon className="h-6 w-6" /></div><h3 className="mt-6 text-xl font-extrabold text-midnight">{e[language][0]}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{e[language][1]}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-brand">{t.explore}<ArrowRight className="h-4 w-4" /></span></Link>})}</div></div></section>

    <section id="blog" className="container-site py-20 sm:py-28"><div><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-terracotta">Journal</p><h2 className="mt-3 text-4xl font-extrabold tracking-tight text-midnight">{t.blogTitle}</h2><p className="mt-3 max-w-2xl text-lg text-slate-600">{t.blogText}</p></div><div className="mt-10 grid gap-7 md:grid-cols-2"><article className="group overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-card"><div className="h-64 overflow-hidden"><img src={heroImage} alt="Finnish winter" className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /></div><div className="p-7"><p className="text-xs font-bold uppercase tracking-wider text-terracotta">Travel guide</p><h3 className="mt-2 text-2xl font-extrabold text-midnight">{language==='fi'?'Ensimmäinen talvi Suomessa':language==='es'?'Tu primer invierno en Finlandia':'Your first winter in Finland'}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{language==='fi'?'Pukeutuminen, liikkuminen ja parhaat elämykset ensimmäiseen talveen.':language==='es'?'Cómo vestirse, moverse y disfrutar del invierno finlandés.':'How to dress, get around and enjoy the Finnish winter.'}</p></div></article><article className="rounded-3xl border border-slate-200 bg-white p-7 shadow-card"><div className="flex items-center gap-2 text-sm text-terracotta"><Star className="h-4 w-4 fill-current" /> Local favourite</div><h3 className="mt-5 text-2xl font-extrabold text-midnight">{language==='fi'?'Saunakulttuuri selitettynä':language==='es'?'La cultura de la sauna explicada':'Sauna culture explained'}</h3><p className="mt-3 text-base leading-7 text-slate-600">{language==='fi'?'Miksi sauna on suomalaisille enemmän kuin kuuma huone – ja miten koet sen aidosti.':language==='es'?'Por qué la sauna es mucho más que una habitación caliente y cómo vivirla de forma auténtica.':'Why sauna is more than a hot room – and how to experience it authentically.'}</p><div className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-brand">Read story <ArrowRight className="h-4 w-4" /></div></article></div></section>

    <section id="contact" className="bg-midnight py-20 text-white sm:py-28"><div className="container-site grid gap-12 lg:grid-cols-[1fr_.85fr] lg:items-start"><div><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-terracotta">Personal service</p><h2 className="mt-3 text-4xl font-extrabold tracking-tight sm:text-5xl">{t.contactTitle}</h2><p className="mt-5 max-w-xl text-lg leading-8 text-white/65">{t.contactText}</p><div className="mt-8 flex items-start gap-4"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-white/10"><Bot className="h-5 w-5 text-terracotta" /></div><div><h3 className="font-bold">{t.aiTitle}</h3><p className="mt-1 text-sm leading-6 text-white/55">{t.aiText}</p><button type="button" className="mt-3 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-4 py-2 text-sm font-bold hover:bg-white/15">{t.ask}<ArrowRight className="h-4 w-4" /></button></div></div></div><form className="rounded-3xl bg-white p-6 text-slate-900 shadow-2xl sm:p-8" onSubmit={(e)=>e.preventDefault()}><div className="grid gap-5"><label className="text-sm font-bold">{t.name}<input required className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-brand focus:ring-4 focus:ring-brand/10" /></label><label className="text-sm font-bold">{t.email}<input required type="email" className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-brand focus:ring-4 focus:ring-brand/10" /></label><label className="text-sm font-bold">{t.message}<textarea required rows={5} className="mt-2 w-full resize-none rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-brand focus:ring-4 focus:ring-brand/10" /></label><button type="submit" className="inline-flex items-center justify-center gap-2 rounded-xl bg-brand px-6 py-3.5 font-extrabold text-white shadow-lg hover:bg-brand-dark"><Mail className="h-4 w-4" /> {t.send}</button></div></form></div></section>
  </main>;
}
