"use client";
import{useEffect,useState}from"react";import{useParams,useRouter}from"next/navigation";import MediaPicker from "@/components/admin/MediaPicker";
type Locale="fi"|"es"|"en";type T={name:string;shortDescription:string;description:string;locationName:string;seoTitle:string;seoDescription:string}; type DBTranslation=T&{locale:Locale;short_description?:string;location_name?:string;seo_title?:string;seo_description?:string};type Property={id:string;slug:string;property_type:string;region:string|null;max_guests:number;bedrooms:number;bathrooms:number;base_price_eur:number|null;featured:boolean;status:"draft"|"published"|"archived";property_translations:Array<DBTranslation>;property_media?:Array<{sort_order:number;media?:{id:string}}>} ;const empty=():T=>({name:"",shortDescription:"",description:"",locationName:"",seoTitle:"",seoDescription:""});
export default function EditPropertyPage(){
 const params=useParams<{id:string}>();const router=useRouter();const[property,setProperty]=useState<Property|null>(null);const[locale,setLocale]=useState<Locale>("es");const[error,setError]=useState("");const[saving,setSaving]=useState(false);
 const[form,setForm]=useState({slug:"",propertyType:"cabin",region:"",maxGuests:2,bedrooms:1,bathrooms:1,basePriceEur:"",featured:false,status:"draft" as Property["status"]});const[translations,setTranslations]=useState<Record<Locale,T>>({fi:empty(),es:empty(),en:empty()}); const[mediaIds,setMediaIds]=useState<string[]>([]);
 useEffect(()=>{fetch("/api/admin/properties",{cache:"no-store"}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||"Lataus epäonnistui");return b.properties.find((x:Property)=>x.id===params.id) as Property|undefined;}).then(p=>{if(!p)throw new Error("Majoitusta ei löytynyt");setProperty(p);setForm({slug:p.slug,propertyType:p.property_type,region:p.region||"",maxGuests:p.max_guests,bedrooms:p.bedrooms,bathrooms:p.bathrooms,basePriceEur:p.base_price_eur==null?"":String(p.base_price_eur),featured:p.featured,status:p.status});const next={fi:empty(),es:empty(),en:empty()};for(const t of p.property_translations||[])next[t.locale]={name:t.name||"",shortDescription:t.short_description||t.shortDescription||"",description:t.description||"",locationName:t.location_name||t.locationName||"",seoTitle:t.seo_title||t.seoTitle||"",seoDescription:t.seo_description||t.seoDescription||""};setTranslations(next);setMediaIds((p.property_media||[]).sort((a,b)=>a.sort_order-b.sort_order).map((x)=>x.media?.id).filter(Boolean) as string[]);}).catch(e=>setError(e instanceof Error?e.message:"Lataus epäonnistui"));},[params.id]);
 function updateT(field:keyof T,value:string){setTranslations(c=>({...c,[locale]:{...c[locale],[field]:value}}));}
 async function save(){setSaving(true);setError("");try{const r=await fetch("/api/admin/properties",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:params.id,...form,maxGuests:Number(form.maxGuests),bedrooms:Number(form.bedrooms),bathrooms:Number(form.bathrooms),basePriceEur:form.basePriceEur?Number(form.basePriceEur):null,mediaIds,translations})});const b=await r.json();if(!r.ok)throw new Error(b.error||"Tallennus epäonnistui");router.push("/admin/properties");}catch(e){setError(e instanceof Error?e.message:"Tallennus epäonnistui")}finally{setSaving(false)}}
 if(!property&&!error)return <main className="min-h-screen bg-slate-50 p-8"><div className="mx-auto max-w-3xl rounded-2xl bg-white p-8">Ladataan…</div></main>;
 if(!property)return <main className="min-h-screen bg-slate-50 p-8"><div className="mx-auto max-w-3xl rounded-2xl bg-red-50 p-6 text-red-700">{error}</div></main>;
 return <main className="min-h-screen bg-slate-50 px-4 py-8 sm:px-8"><div className="mx-auto max-w-5xl"><div className="flex items-end justify-between"><div><p className="text-sm font-semibold text-emerald-700">CMS / Majoitukset</p><h1 className="mt-1 text-3xl font-bold text-slate-950">{translations.es.name||property.slug}</h1></div><button onClick={()=>router.back()} className="text-sm font-semibold text-slate-600">Takaisin</button></div><div className="mt-8 flex flex-wrap gap-2">{(["draft","published","archived"] as const).map(s=><button key={s} onClick={()=>setForm({...form,status:s})} className={"rounded-full px-4 py-2 text-xs font-bold "+(form.status===s?"bg-slate-950 text-white":"border bg-white text-slate-600")}>{s}</button>)}</div><div className="mt-6 rounded-2xl border bg-white p-6 shadow-sm"><div className="mb-6 flex gap-2">{(["fi","es","en"] as Locale[]).map(l=><button key={l} onClick={()=>setLocale(l)} className={"rounded-lg px-4 py-2 text-sm font-semibold "+(locale===l?"bg-slate-950 text-white":"bg-slate-100")}>{l.toUpperCase()}</button>)}</div><div className="grid gap-5"><Field label={"Nimi ("+locale.toUpperCase()+")"} value={translations[locale].name} onChange={v=>updateT("name",v)}/><Field label="Lyhyt kuvaus" value={translations[locale].shortDescription} onChange={v=>updateT("shortDescription",v)}/><TextArea label="Kuvaus" value={translations[locale].description} onChange={v=>updateT("description",v)}/><Field label="Sijainti" value={translations[locale].locationName} onChange={v=>updateT("locationName",v)}/><Field label="SEO title" value={translations[locale].seoTitle} onChange={v=>updateT("seoTitle",v)}/><TextArea label="SEO description" value={translations[locale].seoDescription} onChange={v=>updateT("seoDescription",v)}/></div><MediaPicker value={mediaIds} onChange={setMediaIds}/><button disabled={saving} onClick={save} className="mt-8 rounded-xl bg-emerald-700 px-6 py-3 font-semibold text-white disabled:opacity-50">{saving?"Tallennetaan…":"Tallenna muutokset"}</button>{error&&<p className="mt-4 text-sm text-red-600">{error}</p>}</div></div></main>;
}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="grid gap-2 text-sm font-medium text-slate-700"><span>{label}</span><input value={value} onChange={e=>onChange(e.target.value)} className="rounded-xl border border-slate-200 px-4 py-3"/></label>}
function TextArea({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="grid gap-2 text-sm font-medium text-slate-700"><span>{label}</span><textarea rows={6} value={value} onChange={e=>onChange(e.target.value)} className="rounded-xl border border-slate-200 px-4 py-3"/></label>}
