"use client";
import { useLocale, useTranslations } from "next-intl";
import { motion } from "framer-motion";
import { Star, Quote } from "lucide-react";
const testimonials = [
{name:"María González",location:"Madrid, Spain",text:{en:"The glass igloo and Northern Lights hunt were magical. Everything was perfectly organized. Best trip of our lives!",es:"El iglú de cristal y la caza de auroras fueron mágicos. Todo perfectamente organizado. ¡El mejor viaje de nuestras vidas!",fi:"Lasi-iglu ja revontulijahti olivat maagisia. Kaikki täydellisesti järjestetty. Elämämme paras matka!"},rating:5,avatar:"MG"},
{name:"Carlos Ruiz",location:"Barcelona, Spain",text:{en:"Husky safari with the kids was unforgettable. The cabin by the lake felt like a dream. Highly recommend Nordic Escape.",es:"El safari en husky con los niños fue inolvidable. La cabaña junto al lago parecía un sueño. Recomendamos Nordic Escape.",fi:"Huskyajelu lasten kanssa oli unohtumaton. Järvimökki tuntui unelmalta. Suosittelemme lämpimästi."},rating:5,avatar:"CR"},
{name:"Laura Fernández",location:"Valencia, Spain",text:{en:"Authentic Finnish sauna experience and beautiful Helsinki. The team helped us plan every detail. Will definitely return!",es:"Experiencia auténtica de sauna finlandesa y precioso Helsinki. El equipo nos ayudó a planificar cada detalle. ¡Volveremos!",fi:"Aito suomalainen saunaelämys ja kaunis Helsinki. Tiimi auttoi suunnittelemaan kaiken. Palaamme ehdottomasti!"},rating:5,avatar:"LF"}];
export function Testimonials(){const t=useTranslations("sections");const locale=useLocale();return <section className="py-20 bg-white"><div className="container-narrow"><div className="text-center mb-14"><h2 className="section-title mb-3">{t("testimonials")}</h2></div><div className="grid grid-cols-1 md:grid-cols-3 gap-6">{testimonials.map((item,i)=><motion.div key={item.name} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.1}} className="relative rounded-2xl bg-slate-50 p-6 border border-slate-100 hover:shadow-soft transition"><Quote className="absolute top-5 right-5 h-8 w-8 text-brand-100"/><div className="flex gap-0.5 mb-4">{Array.from({length:item.rating}).map((_,j)=><Star key={j} className="h-4 w-4 fill-gold-500 text-gold-500"/>)}</div><p className="text-slate-700 leading-relaxed mb-6 relative z-10">"{item.text[locale as keyof typeof item.text]||item.text.en}"</p><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-brand-900 text-white text-sm font-semibold">{item.avatar}</div><div><p className="font-semibold text-brand-900 text-sm">{item.name}</p><p className="text-xs text-slate-500">{item.location}</p></div></div></motion.div>)}</div></div></section>}
