'use client';
import { FormEvent, useEffect, useState } from 'react';
import { Bot, X } from 'lucide-react';
type Language = 'fi' | 'es' | 'en';
const answers = {
  fi: { button:'Kysy tekoälyltä', title:'Suomen kesäloma-avustaja', placeholder:'Esim. haluan rauhallisen mökkiloman...', send:'Kysy', intro:'Kerro millaista kesälomaa haet, niin etsitään sopivia kohteita.', summer:'Mathildedal, Naantali ja Ahvenanmaa ovat hyviä lähtökohtia rauhalliseen 1–2 viikon lomaan.', sauna:'Teijolta ja saaristosta löytyy savusaunoja, järvisaunoja ja merenrantasaunoja.', family:'Naantali sopii perheille Muumimaailman, rantojen ja saariston ansiosta.', default:'Voin auttaa vertailemaan majoituksia ja tekemistä. Kerro alue, matkaseurue ja toivottu lomatyyli.' },
  es: { button:'Preguntar a la IA', title:'Asistente de verano finlandés', placeholder:'Ej. busco una cabaña tranquila...', send:'Preguntar', intro:'Cuéntame qué tipo de verano buscas y compararemos opciones.', summer:'Mathildedal, Naantali y Åland son buenos puntos de partida para una estancia tranquila de 1–2 semanas.', sauna:'En Teijo y el archipiélago hay saunas de humo, saunas junto al lago y saunas junto al mar.', family:'Naantali es una buena base para familias gracias a Moominworld, playas y actividades del archipiélago.', default:'Puedo ayudarte a comparar alojamiento y actividades. Dime la zona y el estilo de vacaciones que buscas.' },
  en: { button:'Ask the AI', title:'Finnish summer advisor', placeholder:'E.g. I want a quiet cottage holiday...', send:'Ask', intro:'Tell me what kind of summer you want and we can compare options.', summer:'Mathildedal, Naantali and Åland are good starting points for a quiet 1–2 week stay.', sauna:'Teijo and the archipelago offer smoke saunas, lakeside saunas and seaside saunas.', family:'Naantali is a good family base with Moominworld, beaches and archipelago activities.', default:'I can help compare accommodation and activities. Tell me the area and the style of holiday you want.' },
};
export default function TravelAdvisor({ language: initialLanguage }: { language?: Language }) {
  const [language, setLanguage] = useState<Language>(initialLanguage || 'fi'); const [open, setOpen] = useState(false); const [question, setQuestion] = useState(''); const [answer, setAnswer] = useState('');
  useEffect(() => { const lang = new URLSearchParams(window.location.search).get('lang'); if (lang === 'fi' || lang === 'es' || lang === 'en') setLanguage(lang); }, []);
  const t = answers[language];
  function ask(e: FormEvent) { e.preventDefault(); const q = question.toLowerCase(); if (/sauna|löyly|savusauna/.test(q)) setAnswer(t.sauna); else if (/muumi|perhe|family|familia/.test(q)) setAnswer(t.family); else if (/mathild|salo|naantali|åland|ahven|summer|kesä|verano/.test(q)) setAnswer(t.summer); else setAnswer(t.default); }
  return <div className="fixed bottom-5 right-5 z-[60]"><button type="button" onClick={()=>setOpen(!open)} className="flex items-center gap-2 rounded-full bg-brand px-5 py-3.5 text-sm font-extrabold text-white shadow-2xl transition hover:-translate-y-0.5 hover:bg-brand-dark"><Bot className="h-5 w-5" /> {t.button}</button>{open && <div className="absolute bottom-16 right-0 w-[min(92vw,390px)] overflow-hidden rounded-2xl border border-slate-200 bg-white text-slate-900 shadow-2xl"><div className="flex items-center justify-between bg-midnight px-5 py-4 text-white"><div className="flex items-center gap-2 font-bold"><Bot className="h-4 w-4 text-terracotta" /> {t.title}</div><button type="button" onClick={()=>setOpen(false)} aria-label="Close"><X className="h-4 w-4" /></button></div><div className="p-5"><p className="text-sm leading-6 text-slate-600">{t.intro}</p>{answer && <div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm leading-6 text-slate-700">{answer}</div>}<form onSubmit={ask} className="mt-4 flex gap-2"><input value={question} onChange={(e)=>setQuestion(e.target.value)} required placeholder={t.placeholder} className="min-w-0 flex-1 rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-brand" /><button type="submit" className="rounded-xl bg-brand px-4 py-2.5 text-sm font-bold text-white hover:bg-brand-dark">{t.send}</button></form></div></div>}</div>;
}