'use client';
import { FormEvent, useEffect, useState } from 'react';
import { Bot, X, Sparkles, ArrowUpRight } from 'lucide-react';
type Language = 'fi' | 'es' | 'en';
const answers = {
  fi: { button:'Kysy tekoälyltä', title:'Suomen kesäloma-avustaja', placeholder:'Esim. haluan rauhallisen mökkiloman...', send:'Kysy', intro:'Kerro millaista kesälomaa haet, niin etsitään sopivia kohteita.', summer:'Mathildedal, Naantali ja Ahvenanmaa ovat hyviä lähtökohtia rauhalliseen 1–2 viikon lomaan.', sauna:'Teijolta ja saaristosta löytyy savusaunoja, järvisaunoja ja merenrantasaunoja.', family:'Naantali sopii perheille Muumimaailman, rantojen ja saariston ansiosta.', default:'Voin auttaa vertailemaan majoituksia ja tekemistä. Kerro alue, matkaseurue ja toivottu lomatyyli.' },
  es: { button:'Preguntar a la IA', title:'Asistente de verano finlandés', placeholder:'Ej. busco una cabaña tranquila...', send:'Preguntar', intro:'Cuéntame qué tipo de verano buscas y compararemos opciones.', summer:'Mathildedal, Naantali y Åland son buenos puntos de partida para una estancia tranquila de 1–2 semanas.', sauna:'En Teijo y el archipiélago hay saunas de humo, saunas junto al lago y saunas junto al mar.', family:'Naantali es una buena base para familias gracias a Moominworld, playas y actividades del archipiélago.', default:'Puedo ayudarte a comparar alojamiento y actividades. Dime la zona y el estilo de vacaciones que buscas.' },
  en: { button:'Ask the AI', title:'Finnish summer advisor', placeholder:'E.g. I want a quiet cottage holiday...', send:'Ask', intro:'Tell me what kind of summer you want and we can compare options.', summer:'Mathildedal, Naantali and Åland are good starting points for a quiet 1–2 week stay.', sauna:'Teijo and the archipelago offer smoke saunas, lakeside saunas and seaside saunas.', family:'Naantali is a good family base with Moominworld, beaches and archipelago activities.', default:'I can help compare accommodation and activities. Tell me the area and the style of holiday you want.' },
};
export default function TravelAdvisor({ language: initialLanguage }: { language?: Language }) {
  const [language, setLanguage] = useState<Language>(initialLanguage || 'fi'); const [open, setOpen] = useState(false); const [question, setQuestion] = useState(''); const [answer, setAnswer] = useState('');
  useEffect(() => { const lang = new URLSearchParams(window.location.search).get('lang'); if (lang === 'fi' || lang === 'es' || lang === 'en') setLanguage(lang); }, []);
  const t = answers[language];
  function ask(e: FormEvent) { e.preventDefault(); const q = question.toLowerCase(); if (/sauna|löyly|savusauna/.test(q)) setAnswer(t.sauna); else if (/muumi|perhe|family|familia/.test(q)) setAnswer(t.family); else if (/mathild|salo|naantali|åland|ahven|summer|kesä|verano/.test(q)) setAnswer(t.summer); else setAnswer(t.default); }
  return <div className="fixed bottom-5 right-5 z-[60]">{!open && <button type="button" onClick={()=>setOpen(true)} aria-expanded="false" className="group flex items-center gap-2 rounded-full border border-white/20 bg-brand-950/95 px-5 py-3.5 text-sm font-extrabold text-white shadow-2xl shadow-black/20 backdrop-blur-md transition duration-300 hover:-translate-y-1 hover:bg-brand-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gold-300"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-gold-400 text-brand-950"><Sparkles className="h-4 w-4" /></span>{t.button}<ArrowUpRight className="h-4 w-4 transition group-hover:translate-x-0.5 group-hover:-translate-y-0.5" /></button>}{open && <div className="absolute bottom-0 right-0 w-[min(92vw,410px)] overflow-hidden rounded-[1.5rem] border border-white/20 bg-white text-slate-900 shadow-2xl shadow-black/25"><div className="flex items-center justify-between bg-brand-950 px-5 py-4 text-white"><div className="flex items-center gap-2 font-bold"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-gold-400 text-brand-950"><Sparkles className="h-4 w-4" /></span><div><div className="text-sm">{t.title}</div><div className="text-[10px] font-medium uppercase tracking-[.16em] text-white/55">Finland Experience</div></div></div><button type="button" onClick={()=>setOpen(false)} aria-expanded="true" aria-label="Close" className="rounded-full p-2 hover:bg-white/10"><X className="h-4 w-4" /></button></div><div className="p-5"><p className="text-sm leading-6 text-slate-600">{t.intro}</p>{answer && <div className="mt-4 rounded-xl border border-brand-100 bg-brand-50 p-4 text-sm leading-6 text-slate-700">{answer}</div>}<form onSubmit={ask} className="mt-4 flex gap-2"><input value={question} onChange={(e)=>setQuestion(e.target.value)} required placeholder={t.placeholder} aria-label={t.placeholder} className="min-w-0 flex-1 rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-brand focus:ring-2 focus:ring-brand/15" /><button type="submit" className="rounded-xl bg-brand-900 px-4 py-2.5 text-sm font-bold text-white transition hover:bg-brand-800">{t.send}</button></form></div></div>}</div>;
}