'use client';
import Link from 'next/link';
import ConciergeItinerary from './ConciergeItinerary';
import { FormEvent, useState } from 'react';
import { ArrowRight, Compass, Heart, Sparkles, Waves, TreePine, Utensils, Check } from 'lucide-react';

type Lang='fi'|'es'|'en';
type Rec={type:'destination'|'accommodation'|'experience';slug:string;reason:string};
type Item={slug:string;name:Record<string,string>;description:Record<string,string>;verified?:boolean};
type Plan={day:number;title:string;items:Rec[]};

const ui={
 fi:{title:'Suunnitellaan sinun Suomen-matkasi',intro:'Kerro meille omin sanoin, millaista matkaa haaveilet. Concierge rakentaa ehdotuksen vain tarkistetusta Finland Experience -katalogista.',days:'Päivät',people:'Henkilöt',budget:'Budjetti / yö',request:'Millaisesta matkasta haaveilet?',requestPh:'Esimerkiksi: Haluamme puolison kanssa rauhallisen viiden päivän matkan meren äärelle. Sauna, hyvä ruoka ja luonto kiinnostavat.',interests:'Tärkeimmät kiinnostukset',plan:'Luo henkilökohtainen ehdotus',result:'Sinulle suunniteltu lähtökohta',together:'Suunnitellaan tämä yhdessä',name:'Nimi',email:'Sähköposti',send:'Lähetä matkatoive',sent:'Matkatoiveesi on vastaanotettu.',sentText:'Voimme auttaa viimeistelemään suunnitelmaa ja ohjata sinut tarvittaessa suoraan sopivalle palveluntarjoajalle.',verified:'Tarkistetusta katalogista',note:'Tämä on inspiraatio- ja suunnittelupalvelu, ei varaus. Hinnat, saatavuus ja lopulliset ehdot vahvistetaan aina palveluntarjoajalta.'},
 es:{title:'Diseñemos tu viaje a Finlandia',intro:'Cuéntanos con tus propias palabras qué tipo de viaje sueñas hacer. El concierge utiliza únicamente el catálogo verificado de Finland Experience.',days:'Días',people:'Personas',budget:'Presupuesto / noche',request:'¿Qué tipo de viaje imaginas?',requestPh:'Por ejemplo: Queremos cinco días tranquilos junto al mar, con sauna, buena gastronomía y naturaleza.',interests:'Tus intereses principales',plan:'Crear mi propuesta personal',result:'Tu punto de partida personalizado',together:'Diseñemos esto juntos',name:'Nombre',email:'Correo electrónico',send:'Enviar mi solicitud',sent:'Hemos recibido tu solicitud.',sentText:'Podemos ayudarte a perfeccionar el plan y, cuando corresponda, ponerte en contacto directo con el proveedor adecuado.',verified:'Del catálogo verificado',note:'Esto es un servicio de inspiración y planificación, no una reserva. Los precios, la disponibilidad y las condiciones finales se confirman siempre con el proveedor.'},
 en:{title:'Let’s design your Finland journey',intro:'Tell us in your own words what kind of trip you dream about. The concierge uses only the verified Finland Experience catalogue.',days:'Days',people:'People',budget:'Budget / night',request:'What kind of trip are you imagining?',requestPh:'For example: We want five peaceful days by the sea with sauna, great food and nature.',interests:'Your main interests',plan:'Create my personal plan',result:'Your personalised starting point',together:'Let’s plan this together',name:'Name',email:'Email',send:'Send my request',sent:'We received your request.',sentText:'We can help refine the plan and, when appropriate, connect you directly with the right provider.',verified:'From the verified catalogue',note:'This is an inspiration and planning service, not a booking. Prices, availability and final terms are always confirmed with the provider.'}
} as const;
const choices=[['nature',TreePine,{fi:'Luonto',es:'Naturaleza',en:'Nature'}],['sauna',Sparkles,{fi:'Sauna',es:'Sauna',en:'Sauna'}],['sea',Waves,{fi:'Meri & saaristo',es:'Mar y archipiélago',en:'Sea & archipelago'}],['food',Utensils,{fi:'Ruoka',es:'Gastronomía',en:'Food'}],['romance',Heart,{fi:'Romantiikka',es:'Romántico',en:'Romance'}]] as const;

export default function TripPlanner({language,catalog}:{language:Lang;catalog:{destinations:Item[];accommodations:Item[];experiences:Item[]}}){
 const t=ui[language]; const [days,setDays]=useState('5');const [people,setPeople]=useState('2');const [budget,setBudget]=useState('250');const [question,setQuestion]=useState('');const [selected,setSelected]=useState<string[]>(['nature','sauna','sea']);const [plan,setPlan]=useState<Plan[]>([]);const [summary,setSummary]=useState('');const [recommendations,setRecommendations]=useState<Rec[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [name,setName]=useState('');const [email,setEmail]=useState('');const [sent,setSent]=useState(false);
 const toggle=(x:string)=>setSelected(v=>v.includes(x)?v.filter(y=>y!==x):[...v,x]);
 const resolve=(r:Rec)=>{const list=r.type==='destination'?catalog.destinations:r.type==='accommodation'?catalog.accommodations:catalog.experiences;return list.find(x=>x.slug===r.slug)};
 const path=(r:Rec)=>r.type==='destination'?'destinations':r.type==='accommodation'?'accommodations':'experiences';
 async function create(e:FormEvent){e.preventDefault();setBusy(true);setError('');setSent(false);try{const r=await fetch('/api/concierge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({language,days:Number(days),people:Number(people),budget:Number(budget),interests:selected,question})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Plan could not be created.');setSummary(b.summary||'');setPlan(b.days||[]);setRecommendations(b.recommendations||[]);setTimeout(()=>document.getElementById('concierge-result')?.scrollIntoView({behavior:'smooth',block:'start'}),50)}catch(e){setError(e instanceof Error?e.message:'Unable to create plan.')}finally{setBusy(false)}}
 async function send(e:FormEvent){e.preventDefault();setError('');const r=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({firstName:name,email,locale:language,leadType:'concierge',message:question,source:'concierge-planner',sourcePath:`/${language}/plan`,tripDays:Number(days),tripBudgetEur:Number(budget),tripInterests:selected,tripQuestion:question,recommendedItems:recommendations})});const b=await r.json();if(!r.ok){setError(b.error||'Unable to send request.');return}setSent(true)}
 return <div>
 <section className="rounded-[2rem] bg-brand-950 p-6 text-white shadow-2xl sm:p-10"><div className="flex items-center gap-2 text-gold-300"><Compass className="h-5 w-5"/><span className="text-xs font-bold uppercase tracking-[.2em]">Finland Experience Concierge</span></div><h1 className="mt-4 max-w-4xl font-display text-4xl font-bold leading-tight sm:text-6xl">{t.title}</h1><p className="mt-5 max-w-3xl text-base leading-7 text-white/70 sm:text-lg">{t.intro}</p>
 <form onSubmit={create} className="mt-8 grid gap-6"><div className="grid gap-4 sm:grid-cols-3">{[[t.days,days,setDays,'1','14'],[t.people,people,setPeople,'1','20'],[t.budget,budget,setBudget,'0','100000']].map(([label,value,set,min,max])=><label key={label as string} className="rounded-2xl bg-white/10 p-4"><span className="text-xs font-bold uppercase tracking-wider text-white/60">{label as string}</span><input required type="number" min={min as string} max={max as string} value={value as string} onChange={e=>(set as (v:string)=>void)(e.target.value)} className="mt-2 w-full bg-transparent text-2xl font-bold outline-none"/></label>)}</div>
 <label><span className="text-sm font-bold">{t.request}</span><textarea required minLength={10} maxLength={1500} value={question} onChange={e=>setQuestion(e.target.value)} placeholder={t.requestPh} className="mt-3 min-h-32 w-full rounded-2xl border border-white/10 bg-white/10 p-4 text-sm leading-6 text-white placeholder:text-white/40 outline-none focus:ring-2 focus:ring-gold-300"/></label>
 <div><p className="mb-3 text-sm font-bold">{t.interests}</p><div className="flex flex-wrap gap-2">{choices.map(([key,Icon,label])=><button type="button" key={key} onClick={()=>toggle(key)} className={`inline-flex items-center gap-2 rounded-full border px-4 py-2.5 text-sm font-bold transition ${selected.includes(key)?'border-gold-300 bg-gold-300 text-brand-950':'border-white/20 bg-white/5 text-white hover:bg-white/10'}`}><Icon className="h-4 w-4"/>{label[language]}</button>)}</div></div>
 <button disabled={busy} className="inline-flex w-fit items-center gap-2 rounded-full bg-gold-400 px-6 py-3.5 font-extrabold text-brand-950 transition hover:-translate-y-0.5 disabled:opacity-60">{busy?'…':t.plan}<ArrowRight className="h-4 w-4"/></button>{error&&<p className="text-sm text-red-300">{error}</p>}</form></section>
 {(summary||plan.length>0)&&<section id="concierge-result" className="mt-10 scroll-mt-20"><p className="text-xs font-bold uppercase tracking-[.2em] text-brand-600">{t.result}</p><p className="mt-3 max-w-3xl text-lg leading-8 text-slate-700">{summary}</p>
 <ConciergeItinerary language={language} days={plan} recommendations={recommendations} catalog={catalog} verifiedLabel={t.verified} togetherLabel={t.together}/>

 <div className="mt-8 rounded-[1.5rem] border border-brand-100 bg-brand-50 p-6">{sent?<div><p className="font-bold text-brand-950">{t.sent}</p><p className="mt-1 text-sm text-slate-600">{t.sentText}</p></div>:<><h2 className="font-display text-2xl font-bold text-brand-950">{t.together}</h2><p className="mt-2 text-sm text-slate-600">{t.sentText}</p><form onSubmit={send} className="mt-5 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><input required value={name} onChange={e=>setName(e.target.value)} placeholder={t.name} className="rounded-xl border bg-white px-4 py-3 text-sm"/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder={t.email} className="rounded-xl border bg-white px-4 py-3 text-sm"/><button className="rounded-xl bg-brand-950 px-5 py-3 text-sm font-bold text-white">{t.send}</button></form></>}</div>
 <p className="mt-5 text-xs leading-5 text-slate-500">{t.note}</p></section>}
 </div>
}
