import Link from "next/link";
import { ArrowRight, Building2, Coffee, Sparkles, Waves } from "lucide-react";

export default function CityBreaksPage({ params }: { params: { locale: string } }) {
  const locale=params.locale;
  const copy=locale==="fi"
    ? {eyebrow:"Kaupunki kohtaa Suomen luonnon",title:"Viikonloppu, josta tulee muisto",intro:"Helsinki, Tampere tai Turku — kolme erilaista tapaa nähdä suomalainen kesä.",cities:["Helsinki","Tampere","Turku"],texts:["Meri, design, saunat ja pitkät kesäillat.","Järvimaisemia, kulttuuria ja rentoa kaupunkielämää.","Historiaa, saaristoa ja tunnelmallisia kesäpäiviä."],cta:"Tutki elämyksiä",stay:"Löydä majoitus"}
    : locale==="es"
      ? {eyebrow:"La ciudad se encuentra con la naturaleza",title:"Un fin de semana que recordarás",intro:"Helsinki, Tampere o Turku: tres formas diferentes de vivir el verano finlandés.",cities:["Helsinki","Tampere","Turku"],texts:["Mar, diseño, saunas y largas tardes de verano.","Lagos, cultura y una ciudad relajada.","Historia, archipiélago y días de verano llenos de ambiente."],cta:"Descubrir experiencias",stay:"Encontrar alojamiento"}
      : {eyebrow:"Where city meets Finnish nature",title:"A weekend worth remembering",intro:"Helsinki, Tampere or Turku — three different ways to experience Finnish summer.",cities:["Helsinki","Tampere","Turku"],texts:["Sea, design, saunas and long summer evenings.","Lakes, culture and a relaxed city rhythm.","History, archipelago and atmospheric summer days."],cta:"Explore experiences",stay:"Find a place to stay"};
  const icons=[Building2,Waves,Coffee];
  return <div className="bg-white">
    <section className="bg-brand-950 text-white"><div className="container-narrow py-16 sm:py-24"><p className="text-sm font-semibold uppercase tracking-[.22em] text-white/60">{copy.eyebrow}</p><h1 className="mt-4 max-w-4xl font-display text-5xl font-bold leading-[1.04] sm:text-7xl">{copy.title}</h1><p className="mt-6 max-w-3xl text-xl leading-relaxed text-white/80">{copy.intro}</p></div></section>
    <section className="container-narrow py-14 sm:py-20"><div className="grid gap-6 md:grid-cols-3">
      {copy.cities.map((city,i)=>{const Icon=icons[i];return <article key={city} className="group rounded-[2rem] bg-brand-50 p-7 shadow-soft transition hover:-translate-y-1 hover:shadow-card"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-white text-brand-800 shadow-sm"><Icon className="h-5 w-5"/></div><h2 className="mt-7 font-display text-3xl font-bold text-brand-950">{city}</h2><p className="mt-3 leading-7 text-slate-600">{copy.texts[i]}</p><Link href={`/${locale}/experiences`} className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-brand-800">{copy.cta}<ArrowRight className="h-4 w-4 transition group-hover:translate-x-1"/></Link></article>})}
    </div></section>
    <section className="bg-slate-50"><div className="container-narrow py-14"><div className="rounded-[2rem] bg-white p-8 shadow-soft sm:p-10"><Sparkles className="h-7 w-7 text-amber-500"/><h2 className="mt-5 font-display text-3xl font-bold text-brand-950 sm:text-4xl">{locale==="fi"?"Yhdistä kaupunki ja mökkipäivä.":locale==="es"?"Combina la ciudad con una escapada junto al lago.":"Combine the city with a lake escape."}</h2><p className="mt-4 max-w-2xl text-lg leading-relaxed text-slate-600">{locale==="fi"?"Aloita viikonloppu kaupungin valoista ja jatka matkaa järven rannalle.":locale==="es"?"Empieza con las luces de la ciudad y continúa hacia la tranquilidad del lago.":"Start among city lights and continue towards the quiet of the lake."}</p><Link href={`/${locale}/accommodations`} className="mt-7 inline-flex items-center gap-2 rounded-full bg-brand-900 px-6 py-3.5 text-sm font-bold text-white">{copy.stay}<ArrowRight className="h-4 w-4"/></Link></div></div></section>
  </div>;
}