import Link from "next/link";
import { setRequestLocale } from "next-intl/server";
import { Hero } from "@/components/home/Hero";
import { CabinCard } from "@/components/ui/CabinCard";
import { ExperienceCard } from "@/components/ui/ExperienceCard";
import { destinations,cabins,experiences } from "@/lib/data";
import { events } from "@/lib/events";
import { ArrowRight,CalendarDays,Heart,MapPin,Mountain,Sauna,Ship,TreePine,Waves } from "lucide-react";

const content={
 fi:{introEy:"SUOMEN KESÄ",intro:"Tee lomasta paikka, ei pakettia.",introText:"Nordic Escape auttaa löytämään suomalaisen kesän aidot paikat: majoitukset, saunat, saariston, tapahtumat ja paikalliset elämykset. Varaat suoraan palveluntarjoajalta.",discover:"Tutustu Suomen kesään",destTitle:"Minne seuraavaksi?",destText:"Mathildedalista Naantaliin ja Kemiönsaaren saaristoon – valitse maisema, joka tuntuu omalta.",stayTitle:"Nuku lähellä sitä, mistä Suomi tunnetaan.",stayText:"Valitse mökki, huvila, huone tai glamping. Katso kuvat, hinnat ja palvelut ja siirry palveluntarjoajan omalle sivulle.",experienceTitle:"Päivät, jotka muistat vielä kotona.",experienceText:"Sauna järven rannalla. Melonta saaristossa. Pyöräily kylästä toiseen. Iltatori ja jäätelö vanhassa kaupungissa.",eventTitle:"Tapahtumat tekevät matkasta elävän.",eventText:"Kurpitsaviikot, kesätorit, joulumarkkinat, saaristopäivät ja Naantalin kesä. Katso mitä tapahtuu juuri silloin, kun olet tulossa.",allEvents:"Katso tapahtumakalenteri",regions:["Mathildedal & Salo","Naantali & Archipelago","Åland","Kemiönsaari"]},
 es:{introEy:"VERANO FINLANDÉS",intro:"Haz del destino una experiencia, no un paquete.",introText:"Nordic Escape te ayuda a descubrir el Finlandia auténtica: alojamientos, saunas, archipiélago, eventos y experiencias locales. Reserva directamente con el proveedor.",discover:"Explora el verano finlandés",destTitle:"¿Adónde vamos?",destText:"De Mathildedal a Naantali y el archipiélago de Kimitoön: elige el paisaje que te llama.",stayTitle:"Duerme cerca de lo que hace especial a Finlandia.",stayText:"Cabañas, villas, habitaciones y glamping. Mira fotos, precios y servicios y continúa directamente al proveedor.",experienceTitle:"Días que recordarás al volver a casa.",experienceText:"Sauna junto al lago. Kayak entre islas. Bicicleta por pueblos. Mercados de verano y helado en el casco antiguo.",eventTitle:"Los eventos hacen que el viaje cobre vida.",eventText:"Calabazas, mercados de verano, Navidad, días de archipiélago y el verano de Naantali. Descubre qué ocurre durante tu estancia.",allEvents:"Ver calendario de eventos",regions:["Mathildedal y Salo","Naantali y archipiélago","Åland","Kimitoön"]},
 en:{introEy:"FINNISH SUMMER",intro:"Make the destination the experience.",introText:"Nordic Escape helps you discover authentic Finland: stays, saunas, archipelago, events and local experiences. Book directly with the provider.",discover:"Explore Finnish summer",destTitle:"Where will you go next?",destText:"From Mathildedal to Naantali and the Kimitoön archipelago – choose the landscape that calls you.",stayTitle:"Sleep close to what makes Finland special.",stayText:"Cottages, villas, rooms and glamping. See photos, prices and facilities, then continue directly to the provider.",experienceTitle:"Days you will remember long after you leave.",experienceText:"Sauna by the lake. Kayaking between islands. Cycling through villages. Summer markets and ice cream in the old town.",eventTitle:"Events make a journey come alive.",eventText:"Pumpkin weeks, summer markets, Christmas, archipelago days and Naantali summer. See what is happening while you are here.",allEvents:"Explore the event calendar",regions:["Mathildedal & Salo","Naantali & Archipelago","Åland","Kimitoön"]}} as const;

export default function HomePage({params}:{params:{locale:string}}){const locale=params.locale as keyof typeof content;setRequestLocale(locale);const c=content[locale]||content.en;const featuredCabins=cabins.slice(0,3);const featuredExperiences=experiences.slice(0,3);const future=events.filter(e=>e.end?e.end>="2026-09-28":e.start>="2026-09-28").slice(0,3);return <main className="bg-white"><Hero/>
<section className="relative z-20 -mt-7"><div className="container-narrow"><div className="grid overflow-hidden rounded-3xl border border-white/50 bg-white/95 shadow-2xl shadow-slate-900/10 backdrop-blur md:grid-cols-3"><div className="p-6 md:col-span-2"><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-700">{c.introEy}</p><h2 className="mt-2 font-display text-2xl font-black tracking-tight text-slate-950 sm:text-3xl">{c.intro}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">{c.introText}</p></div><Link href={`/${locale}/destinations`} className="group flex items-center justify-between bg-slate-950 p-6 text-white"><span className="font-black">{c.discover}</span><ArrowRight className="h-5 w-5 transition group-hover:translate-x-1"/></Link></div></div></section>
<section className="py-24"><div className="container-narrow"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-700">01 · PLACES</p><h2 className="mt-3 font-display text-4xl font-black tracking-tight text-slate-950 sm:text-5xl">{c.destTitle}</h2><p className="mt-4 text-lg leading-8 text-slate-600">{c.destText}</p></div><div className="mt-10 grid gap-4 md:grid-cols-4">{destinations.filter(d=>d.featured).slice(0,4).map((d,i)=><Link key={d.id} href={`/${locale}/destinations/${d.slug}`} className={`group relative overflow-hidden rounded-3xl ${i===0?"md:col-span-2 md:row-span-2":"md:col-span-1"} min-h-64 bg-slate-900`}><img src={d.image} alt={d.name[locale]||d.name.en} className="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/15 to-transparent"/><div className="absolute inset-x-5 bottom-5 text-white"><p className="text-xs font-bold uppercase tracking-widest text-white/70">{c.regions[i]||"Finland"}</p><h3 className="mt-1 text-2xl font-black">{d.name[locale]||d.name.en}</h3><span className="mt-2 inline-flex items-center gap-1 text-sm font-bold">{c.discover}<ArrowRight className="h-4 w-4"/></span></div></Link>)}</div></div></section>
<section className="bg-[#f2f5f1] py-24"><div className="container-narrow"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-700">02 · STAYS</p><h2 className="mt-3 font-display text-4xl font-black tracking-tight text-slate-950 sm:text-5xl">{c.stayTitle}</h2><p className="mt-5 text-lg leading-8 text-slate-600">{c.stayText}</p><Link href={`/${locale}/accommodations`} className="mt-7 inline-flex items-center gap-2 rounded-full bg-slate-950 px-6 py-3.5 text-sm font-black text-white">{c.discover}<ArrowRight className="h-4 w-4"/></Link></div><div className="grid gap-5 md:grid-cols-3">{featuredCabins.map((cabin,i)=><CabinCard key={cabin.id} cabin={cabin} index={i}/>)}</div></div></div></section>
<section className="py-24"><div className="container-narrow"><div className="grid gap-12 lg:grid-cols-[1fr_1fr]"><div><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-700">03 · EXPERIENCES</p><h2 className="mt-3 font-display text-4xl font-black tracking-tight text-slate-950 sm:text-5xl">{c.experienceTitle}</h2><p className="mt-5 text-lg leading-8 text-slate-600">{c.experienceText}</p><div className="mt-8 grid grid-cols-2 gap-3 text-sm font-bold text-slate-700"><div className="rounded-2xl bg-slate-50 p-4"><Sauna className="mb-3 h-6 w-6 text-emerald-700"/>Private sauna</div><div className="rounded-2xl bg-slate-50 p-4"><Ship className="mb-3 h-6 w-6 text-emerald-700"/>Archipelago</div><div className="rounded-2xl bg-slate-50 p-4"><TreePine className="mb-3 h-6 w-6 text-emerald-700"/>Nature</div><div className="rounded-2xl bg-slate-50 p-4"><Heart className="mb-3 h-6 w-6 text-emerald-700"/>Slow travel</div></div></div><div className="grid gap-5 md:grid-cols-3 lg:grid-cols-1">{featuredExperiences.map((e,i)=><ExperienceCard key={e.id} experience={e} index={i}/>)}</div></div></div></section>
<section className="bg-slate-950 py-24 text-white"><div className="container-narrow"><div className="flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div className="max-w-2xl"><p className="text-xs font-black uppercase tracking-[.2em] text-amber-300">04 · EVENTS</p><h2 className="mt-3 font-display text-4xl font-black tracking-tight sm:text-5xl">{c.eventTitle}</h2><p className="mt-4 text-lg leading-8 text-white/65">{c.eventText}</p></div><Link href={`/${locale}/events`} className="inline-flex shrink-0 items-center gap-2 rounded-full bg-white px-6 py-3.5 text-sm font-black text-slate-950">{c.allEvents}<ArrowRight className="h-4 w-4"/></Link></div><div className="mt-10 grid gap-5 md:grid-cols-3">{future.map(e=><Link key={e.id} href={`/${locale}/events`} className="group overflow-hidden rounded-3xl bg-white/10 ring-1 ring-white/10"><div className="aspect-[16/9] overflow-hidden"><img src={e.image} alt={e.title[locale]||e.title.en} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/></div><div className="p-5"><div className="flex items-center gap-2 text-xs font-bold text-emerald-300"><CalendarDays className="h-4 w-4"/>{e.start}{e.end&&` – ${e.end}`}</div><h3 className="mt-2 text-xl font-black">{e.title[locale]||e.title.en}</h3><p className="mt-2 text-sm leading-6 text-white/60">{e.excerpt[locale]||e.excerpt.en}</p></div></Link>)}</div></div></section>
<section className="py-24"><div className="container-narrow"><div className="overflow-hidden rounded-[2rem] bg-gradient-to-br from-emerald-950 via-slate-950 to-slate-900 px-7 py-14 text-center text-white sm:px-14"><Waves className="mx-auto h-9 w-9 text-amber-300"/><h2 className="mt-5 font-display text-3xl font-black sm:text-5xl">Your Finnish summer starts here.</h2><p className="mx-auto mt-4 max-w-2xl text-white/65">Find a place you love. Discover what is happening nearby. Then book directly with the people who make the experience.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Link href={`/${locale}/accommodations`} className="rounded-full bg-amber-300 px-7 py-3.5 text-sm font-black text-slate-950">Find your stay</Link><Link href={`/${locale}/events`} className="rounded-full border border-white/20 bg-white/10 px-7 py-3.5 text-sm font-black text-white">See events</Link></div></div></div></section>
</main>}
