ALTER TABLE public.site_pages ADD COLUMN IF NOT EXISTS blocks JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS homepage_slides JSONB NOT NULL DEFAULT '[]'::jsonb;
CREATE TABLE IF NOT EXISTS public.cms_revisions (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), entity_type text NOT NULL, entity_id text NOT NULL,
 locale text, payload jsonb NOT NULL, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
 created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS cms_revisions_entity_idx ON public.cms_revisions(entity_type,entity_id,created_at DESC);
ALTER TABLE public.cms_revisions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "cms revisions admin read" ON public.cms_revisions;
CREATE POLICY "cms revisions admin read" ON public.cms_revisions FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id=auth.uid() AND p.role IN ('SUPER_ADMIN','ADMIN','CONTENT_MANAGER','EDITOR')));
DROP POLICY IF EXISTS "cms revisions admin insert" ON public.cms_revisions;
CREATE POLICY "cms revisions admin insert" ON public.cms_revisions FOR INSERT TO authenticated WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id=auth.uid() AND p.role IN ('SUPER_ADMIN','ADMIN','CONTENT_MANAGER','EDITOR')));


INSERT INTO public.site_settings (singleton, homepage_slides, updated_at)
VALUES (
 true,
 '[
  {"id":"summer","imageUrl":"https://commons.wikimedia.org/wiki/Special:Redirect/file/Turku_archipelago_house.jpg","credit":"Henri Sivonen / Wikimedia Commons","creditUrl":"https://commons.wikimedia.org/wiki/File:Turku_archipelago_house.jpg","href":"/destinations","durationMs":3000,"enabled":true,"copy":{"fi":{"eyebrow":"Hidden Coastal Finland","title":"Suomen kesä alkaa rannikon pienistä paikoista","text":"Pitkiä iltoja, saaristoa, ruukkikyliä ja rauhallisia mökkipäiviä.","cta":"Tutustu kohteisiin"},"es":{"eyebrow":"Hidden Coastal Finland","title":"El verano finlandés empieza en la costa","text":"Largas tardes, archipiélago, pueblos históricos y cabañas tranquilas.","cta":"Explorar destinos"},"en":{"eyebrow":"Hidden Coastal Finland","title":"Finnish summer begins in the small places on the coast","text":"Long evenings, archipelago islands, ironworks villages and quiet cottage days by the water.","cta":"Explore destinations"}}},
  {"id":"cottage","imageUrl":"https://commons.wikimedia.org/wiki/Special:Redirect/file/Finnish_summer_cottage_and_a_lake_in_Keuruu.jpg","credit":"Kospo75 / Wikimedia Commons","creditUrl":"https://commons.wikimedia.org/wiki/File:Finnish_summer_cottage_and_a_lake_in_Keuruu.jpg","href":"/accommodations","durationMs":3000,"enabled":true,"copy":{"fi":{"eyebrow":"Suomen mökkikesä","title":"Aamukahvi veden äärellä","text":"Valoisa mökkipäivä alkaa järven rannalta – oma sauna, laituri ja luonto aivan vieressä.","cta":"Katso majoituksia"},"es":{"eyebrow":"Verano en una cabaña finlandesa","title":"Café junto al agua","text":"Un día de verano junto al lago, con sauna privada, embarcadero y naturaleza alrededor.","cta":"Ver alojamientos"},"en":{"eyebrow":"Finnish cottage summer","title":"Morning coffee by the water","text":"A bright summer day by the lake, with a private sauna, jetty and nature at your doorstep.","cta":"See stays"}}},
  {"id":"archipelago","imageUrl":"https://commons.wikimedia.org/wiki/Special:Redirect/file/Turku_Archipelago.jpg","credit":"Rob Sinclair / Wikimedia Commons","creditUrl":"https://commons.wikimedia.org/wiki/File:Turku_Archipelago.jpg","href":"/destinations","durationMs":3000,"enabled":true,"copy":{"fi":{"eyebrow":"Turun saaristo","title":"Sininen meri, sileät kalliot","text":"Saariston kesä näyttää parhaat puolensa kirkkaassa päivänvalossa.","cta":"Tutustu saaristoon"},"es":{"eyebrow":"Archipiélago de Turku","title":"Mar azul y rocas lisas","text":"El verano del archipiélago en su versión más luminosa y auténtica.","cta":"Explorar el archipiélago"},"en":{"eyebrow":"Turku Archipelago","title":"Blue water, sun-warmed rocks","text":"The Finnish archipelago at its brightest – open water, pine trees and summer light.","cta":"Explore the archipelago"}}},
  {"id":"hanko","imageUrl":"https://commons.wikimedia.org/wiki/Special:Redirect/file/Hanko_aerial_1.jpg","credit":"Kallerna / Wikimedia Commons","creditUrl":"https://commons.wikimedia.org/wiki/File:Hanko_aerial_1.jpg","href":"/destinations/hanko","durationMs":3000,"enabled":true,"copy":{"fi":{"eyebrow":"Hanko · Suomen eteläkärki","title":"Meri, hiekka ja pitkä kesäpäivä","text":"Hanko yhdistää rannat, puutalot ja saariston raikkaan merituulen.","cta":"Tutustu Hankoon"},"es":{"eyebrow":"Hanko · extremo sur de Finlandia","title":"Mar, arena y un largo día de verano","text":"Playas, casas de madera y el aire fresco del Báltico.","cta":"Explorar Hanko"},"en":{"eyebrow":"Hanko · Finland's southern coast","title":"Sea, sand and a long summer day","text":"Beaches, wooden houses and the fresh breeze of the Baltic Sea.","cta":"Explore Hanko"}}},
  {"id":"naantali","imageUrl":"https://commons.wikimedia.org/wiki/Special:Redirect/file/Naantali_harbour_and_church.jpg","credit":"Pöllö / Wikimedia Commons","creditUrl":"https://commons.wikimedia.org/wiki/File:Naantali_harbour_and_church.jpg","href":"/destinations/naantali","durationMs":3000,"enabled":true,"copy":{"fi":{"eyebrow":"Naantali","title":"Kesä alkaa vanhasta satamasta","text":"Värikkäät puutalot, meri ja saariston portti tekevät Naantalista täydellisen kesäpäivän.","cta":"Tutustu Naantaliin"},"es":{"eyebrow":"Naantali","title":"El verano comienza en el puerto antiguo","text":"Casas de madera, mar y la puerta de entrada al archipiélago.","cta":"Explorar Naantali"},"en":{"eyebrow":"Naantali","title":"Summer begins at the old harbour","text":"Colourful wooden houses, the sea and the gateway to the archipelago.","cta":"Explore Naantali"}}},
  {"id":"mathildedal","imageUrl":"https://commons.wikimedia.org/wiki/Special:Redirect/file/Anttipoffi_workers%27_quarters_in_Mathildedal.jpg","credit":"Kotivalo / Wikimedia Commons","creditUrl":"https://commons.wikimedia.org/wiki/File:Anttipoffi_workers%27_quarters_in_Mathildedal.jpg","href":"/destinations/mathildedal","durationMs":3000,"enabled":true,"copy":{"fi":{"eyebrow":"Mathildedal · Salo","title":"Pieni ruukkikylä, suuri tunnelma","text":"Käsityöläisiä, kahviloita, merta ja metsäpolkuja yhden rauhallisen kylän ympärillä.","cta":"Tutustu Mathildedaliin"},"es":{"eyebrow":"Mathildedal · Salo","title":"Un pequeño pueblo con mucho carácter","text":"Artesanía, cafés, mar y senderos junto a un histórico pueblo industrial.","cta":"Explorar Mathildedal"},"en":{"eyebrow":"Mathildedal · Salo","title":"A small village with a big atmosphere","text":"Crafts, cafés, sea and forest trails around a historic ironworks village.","cta":"Explore Mathildedal"}}},
  {"id":"aland","imageUrl":"https://commons.wikimedia.org/wiki/Special:Redirect/file/Kastelholm_2026-08-09_image12.jpg","credit":"Håkan Skogsjö / Wikimedia Commons","creditUrl":"https://commons.wikimedia.org/wiki/File:Kastelholm_2026-08-09_image12.jpg","href":"/destinations/aland","durationMs":3000,"enabled":true,"copy":{"fi":{"eyebrow":"Ahvenanmaa","title":"Saariston valo jatkuu horisonttiin","text":"Meri, kalliosaaret ja kesän kirkas pohjoismainen valo.","cta":"Tutustu Ahvenanmaahan"},"es":{"eyebrow":"Åland","title":"La luz del archipiélago llega hasta el horizonte","text":"Mar, islas rocosas y la luz nórdica del verano.","cta":"Explorar Åland"},"en":{"eyebrow":"Åland","title":"Archipelago light all the way to the horizon","text":"Sea, rocky islands and bright Nordic summer light.","cta":"Explore Åland"}}},
  {"id":"porvoo","imageUrl":"https://commons.wikimedia.org/wiki/Special:Redirect/file/Porvoo_old_town.jpg","credit":"Teemu Eskola / Wikimedia Commons","creditUrl":"https://commons.wikimedia.org/wiki/File:Porvoo_old_town.jpg","href":"/destinations/porvoo","durationMs":3000,"enabled":true,"copy":{"fi":{"eyebrow":"Porvoo","title":"Vanhan kaupungin kesäpäivä","text":"Punaiset ranta-aitat, jokimaisema ja historiallinen keskusta kutsuvat hidastamaan.","cta":"Tutustu Porvooseen"},"es":{"eyebrow":"Porvoo","title":"Un día de verano en el casco antiguo","text":"Casas rojas junto al río, historia y cafés para disfrutar sin prisa.","cta":"Explorar Porvoo"},"en":{"eyebrow":"Porvoo","title":"A summer day in the old town","text":"Red riverside warehouses, historic streets and cafés made for slowing down.","cta":"Explore Porvoo"}}},
  {"id":"hankoBeach","imageUrl":"https://commons.wikimedia.org/wiki/Special:Redirect/file/Regattanranta_beach_in_the_city_center_of_Hanko,_Finland,_2021.jpg","credit":"W.carter / Wikimedia Commons","creditUrl":"https://commons.wikimedia.org/wiki/File:Regattanranta_beach_in_the_city_center_of_Hanko,_Finland,_2021.jpg","href":"/destinations/hanko","durationMs":3000,"enabled":true,"copy":{"fi":{"eyebrow":"Hanko · rannikko","title":"Paljain jaloin kesään","text":"Aurinkoinen hiekkaranta ja meri – Suomen etelärannikon kesä parhaimmillaan.","cta":"Tutustu Hankoon"},"es":{"eyebrow":"Hanko · costa","title":"Camina descalzo hacia el verano","text":"Playa soleada y mar abierto en la costa sur de Finlandia.","cta":"Explorar Hanko"},"en":{"eyebrow":"Hanko · coast","title":"Walk barefoot into summer","text":"A sunlit sandy beach and open sea on Finland's southern coast.","cta":"Explore Hanko"}}},
  {"id":"herrankukkaro","imageUrl":"https://le-de.cdn-website.com/437c2bac51dd486c80c3e153a9033393/dms3rep/multi/opt/Kuva8-8066abf8-1920w.jpg","credit":"Herrankukkaro","href":"https://www.herrankukkaro.fi/","external":true,"durationMs":3000,"enabled":true,"copy":{"fi":{"eyebrow":"Rymättylä · Naantali","title":"Savusauna meren äärellä","text":"Herrankukkaro yhdistää saariston, savusaunan, majoituksen ja paikalliset maut.","cta":"Siirry palveluntarjoajalle"},"es":{"eyebrow":"Rymättylä · Naantali","title":"Sauna de humo junto al mar","text":"Herrankukkaro combina archipiélago, sauna de humo, alojamiento y gastronomía local.","cta":"Ir al proveedor"},"en":{"eyebrow":"Rymättylä · Naantali","title":"Smoke sauna by the sea","text":"Herrankukkaro brings together archipelago nature, smoke sauna, accommodation and local food.","cta":"Visit provider"}}}
 ]'::jsonb,
 now()
)
ON CONFLICT (singleton) DO UPDATE SET homepage_slides = CASE WHEN public.site_settings.homepage_slides = '[]'::jsonb THEN EXCLUDED.homepage_slides ELSE public.site_settings.homepage_slides END, updated_at = now();
